### ISSUE TITLE
Save funktion not working with edited Script

### ISSUE THREAD

**Issue by DaTroll** [Frodo45127/rpfm#1]
Hi there,

here my step by step order to reproduce:

1. Open mod
2. Edit script
3. Save mod: get save confirmation from RPFM
4. close mod
5. reopen mod: previously made changes are not saved!

Thanks for you hard work!

**Comment by Frodo45127** [comment]
Mmm between steps 2 and 3, did you pressed the big wide "Save to PackedFile" button above the script? Text files are not saved on edit, like the tables, but when you press that button.

**Comment by DaTroll** [comment]
oh... ok. Now it worked. It's a bit unintuitive. Maybe you can make it save to packfile automatically or at least give a warning if there are unsaved changes?

**Comment by Frodo45127** [comment]
Haven't found a proper way to do it yet, that's why there is a button. If I manage to find a way to do it automatically without the problems I encountered before, I'll implement it, but for now it needs to be done manually. Guess with this I can close the issue.
