### ISSUE TITLE
Global Search doesn't work with integer or real type attributes.

### ISSUE THREAD

**Issue by gwtwind** [Frodo45127/rpfm#103]
**Describe your problem**
Global search can't find with integer or real type values. It seems only works with varchar type. Regex search also.

Is there any special usage with number types?

**Extra info?**
RPFM version 1.6.2

**Comment by Frodo45127** [comment]
Yeah, known bug. The global search thing only works with string cells. I plan to improve it but.... always there is another thing more urgent to do first.....

**Comment by Frodo45127** [comment]
Fixed in 2.0 if I remember correctly.
