### ISSUE TITLE
Extract whole db as tsv file

### ISSUE THREAD

**Issue by AlcoholV** [Frodo45127/rpfm#104]
Thank you for making a great tool.
I would like RPFM have a feature to extract the entire db as a tsv file.
It will be very helpful when using git to commit or compare with diff for version control. 
It's uncomfortable now, because it's only support extracting as a binary file.

Thank you.

**Comment by Frodo45127** [comment]
That's already implemented. Open a PackFile, right-click it, then go to "Create" and there you have "Mass-Import/Export TSV". "Mass-Import" allows you to import a bunch of TSV files for DB tables or Locs at the same time. "Mass-Export" exports every db/loc in a PackFile to TSV files.

Just remember these options are only available if you configured the game's path in the "Preferences" window.

And if you want to do it for individual files, just open it, right-click in any place inside the open table and you'll see an "Import/Export TSV" button somewhere (don't remember exactly where).

**Comment by AlcoholV** [comment]
Thank you. 
I've always seen it, but I didn't think it was under the Create menu.
