### ISSUE TITLE
Compilation instructions are slightly off. QT5.8 no longer sufficient

### ISSUE THREAD

**Issue by Dirk-c-Walter** [Frodo45127/rpfm#105]
The compilation guide and readme say that you need QT5.8+ but in fact you need 5.11+ since that is when "QAbstractItemView::eventFilter" was introduced.

**Comment by Frodo45127** [comment]
Mmmmm and where does RPFM uses that? The 5.8 minimum is due to the qt crate being done for 5.8, not supporting newer stuff.

**Comment by dsr085** [comment]
Copy pasted from readme. "* ***Qt 5.8*** or higher."

**Comment by Frodo45127** [comment]
mmm I know, but the question remains the same: where does RPFM uses something not supported by Qt 5.8?

**Comment by dsr085** [comment]
Misunderstanding on my part. Thought question was about 5.8+ not the "QAbstractItemView::eventFilter".
