### ISSUE TITLE
Wrong table column order/name in table

### ISSUE THREAD

**Issue by DerFisc** [Frodo45127/rpfm#107]
The columns in "cai_personality_captive_components" table seem to be wrongly assigned.
It appears "Bias Kill" and "Bias Enslave" are switched when compared to the Dave table.

**Extra info?**
I used the newest version of the tool and schema (downloaded it today).
[
![Capture2](https://user-images.githubusercontent.com/15892552/73614499-ee95e780-45ff-11ea-898f-557e21a7b250.PNG)
](url)
https://user-images.githubusercontent.com/15892552/73614499-ee95e780-45ff-11ea-898f-557e21a7b250.PNG

**Comment by Frodo45127** [comment]
Thanks for the report! I'll try to get it fixed for this next weekend.

**Comment by Frodo45127** [comment]
Should be fixed with the schema update I just uploaded.
