### ISSUE TITLE
TW: Arena schemas.

### ISSUE THREAD

**Issue by Oleksandr-Kononiuk** [Frodo45127/rpfm#109]
Sorry its not issue, just want get some info from u. TW: Arena start publishing in China, so I decide to share Arena schema tables to you. Schemas not fully completed and most of column name are not named, cause i don`t have idea what data are they connected with. 
At last 2 question:
1) Is needed send u updated Arena schemas in future? Is it interesting for u?
2) Is it possible to see in future in RPFM function to pack back game data? Is it possible to implement it?

[schemas.zip](https://github.com/Frodo45127/rpfm/files/4539961/schemas.zip)

**Comment by Trolldemorted** [comment]
Does TWA CN use the same pack encryption like the normal TWA?

**Comment by Oleksandr-Kononiuk** [comment]
yeap, in March was first stage of CBT, and i was decrypt~80% interesting files

**Comment by Trolldemorted** [comment]
Are there files rpfm/tw_unpack cannot decrypt?

**Comment by Oleksandr-Kononiuk** [comment]
No, I was unpack all pack_name.pack files. 
In previous message I meant "decrypt 80% DB files using HexEditor (Decoder)". Sorry for not specifying.

**Comment by Frodo45127** [comment]
About Arena, yeah, I know it has been published in China. It's just I don't really have time to set up everything needed to download it, and support for it has always been minimal. 

If you want to continue decoding tables, sure, keep sending me the schemas and I'll put them in the repo, so RPFM can update them like the rest. Either that or fork the repo, and open a pr with the schemas changed. I'll see if later today/tomorrow I can check them and push them into the repo.

**Comment by Frodo45127** [comment]
Schema updated.
