### ISSUE TITLE
New MyMod does not automatically select Default Game from Preferences

### ISSUE THREAD

**Issue by GreetingsGQ** [Frodo45127/rpfm#110]
New MyMod does not automatically select the Default Game that is specified in Preferences.

1.6.2 defaults to Three Kingdoms
2.0.0 defaults to Attila and has an ampersand at the beginning of the window title.

**Comment by Frodo45127** [comment]
the ampersand is a known qt bug sadly, and the new mymod game wasn't the default game in 1.6.2. It's just that the order of the games in the combo was different and that was the first one (I may revert that in the future) but pre-selecting the game selected in that combo is a good idea.

**Comment by Frodo45127** [comment]
Done in the develop branch. Should be in 2.0.1 when it gets released, though it's not using the "default game" but the currently selected one.
