### ISSUE TITLE
Program freezes when renaming multiple tables at once

### ISSUE THREAD

**Issue by robert-d-schultz** [Frodo45127/rpfm#113]
When I select multiple tables (data__) using ctrl+left click, and then try and rename them, the program freezes. Renaming them individually, one at a time, does not result in a freeze.

This is in version 2.0.0.

**Comment by Frodo45127** [comment]
It was an internal deadlock triggered only when multiple files where selected indeed. Fixed in the develop branch. Should be in 2.0.1.
