### ISSUE TITLE
Copy/Pasting many records from one DB table to another similar table causes hang 

### ISSUE THREAD

**Issue by GrouchPotato** [Frodo45127/rpfm#116]
**Describe your problem**

As in the title. Selecting many records from one table, then pasting into a different table of the same category causes a hang. This doesn't happen when selecting only two records.

Steps to reproduce (all of my particular case in case I make a wrong assumption about what's relevant):

Context: 
Modding Warhammer 2, RPFM 2.0.0, Schemas up to date as of 2020:04:03, Windows 10
- Preference: Dependency checked for DB tables -> Disabled (if relevant)

Steps to reproduce:
- Start a packfile and import DB/land_units/data__ from WH2's data.pack.
- Make a new land_units table and call it something else, lets say 'NewTable'
- Create a single blank record in the new table (because you can't paste without first selecting a record to paste over).
- Go back to data__ table and order by 'Class' (I'd guess this isn't relevant, but who knows)
- Select first two records with class 'com' and copy
- Go back to 'NewTable', select first row, and paste. 
--> result: success.
- Now return to 'data__' and select all remaining 'com' records, copy
- Return to 'NewTable' and append a new row to paste over.
- Select new row, and paste
--> result: Hang.

Observations:
In task manager, the process stays at max CPU use for a thread, and memory use gradually increases until maxed out (in this case at around 5Gb).

**Comment by Frodo45127** [comment]
aggg this is because one of the paste optimization from 1.6.2 was not properly moved to 2.0. Another bug to fix in 2.0.1.

**Comment by GrouchPotato** [comment]
:-/ Sorry to be the bearer and all. Thanks for maintaining this!

**Comment by Frodo45127** [comment]
Ok, just fixed it in the develop branch. Paste times are again under one second. Could use a few more optimizations when undoing/redoing a big paste, but that has gone down by a lot too. So, with that, this is fixed for 2.0.1.
