### ISSUE TITLE
Suggestion - Copy Row -> Paste As New Row

### ISSUE THREAD

**Issue by FiftyTifty** [Frodo45127/rpfm#117]
Current version: v2.0.1

In order to copy-paste a row, you need to:

1. Select the entire row, that you want to copy
2. Create a new row in the data table you want to copy to
3. Select the entire new row
4. Press ctrl+v to paste the data

It's fairly clunky. It would save a bit of tedium if we could just right-click -> copy row -> right-click -> paste row.

**Comment by Frodo45127** [comment]
mmm not really. Currently you have to:

1. Select row to copy, and copy
2. Add new row on the other table (it'll get autoselected).
3. Paste.

So... unless I'm mistaken, it's already doing what you're asking for.

**Comment by FiftyTifty** [comment]
You always have to add a new row, select that row, then paste over it. If you have more than one row copied, additional rows will be created automatically. But you still have to create a row first, before you can paste in any rows. Also, you have to overwrite one of the rows.

That's pretty janky. A simple ctrl+c ctrl+v should insert rows, regardless of there being any rows present in the table.

**Comment by Frodo45127** [comment]
You don't have to select that row. It's done automatically. So it's just a matter of add row, paste vs paste as new row. For an user it may seem that "Paste as new row" it's something simple, but from the code perspective, it's quite more complex than chaining two actions. And adding all that complexity to avoid one shortcut its not very... acceptable.

In the case of empty tables though, I can wire up that stuff gets pasted automatically, without adding new rows (that situation can be integrated in the current clever paste code), but for tables with data already in them, the current solution is good enough.

**Comment by Frodo45127** [comment]
mmmm I forgot to close this one. Was done in 2.2 I believe....
