### ISSUE TITLE
Translation files I made(CHN)

### ISSUE THREAD

**Issue by XuXinMing** [Frodo45127/rpfm#118]
I don’t quite understand how to submit a pull request
So can I upload the file here, you can add it to the localized file
Thank you
[Chinese_cn.zip](https://github.com/Frodo45127/rpfm/files/4738663/Chinese_cn.zip)

**Comment by Frodo45127** [comment]
mmmmm you just got lucky. I'm preparing a hotfix because turns out 2.0.1 shipped with a easy-to-trigger CTD..... and just when I was going to upload.... Anyway, I'll do a quick test to ensure the translation works, add it to the repo, and to the new release.

**Comment by XuXinMing** [comment]
Thank you
I supported you on Patreon for $60, But no money was deducted from my credit card
I want to know how to support it only once instead of monthly

**Comment by Frodo45127** [comment]
Thanks for the support!

Patreon only charges at the beginning of the month I think. If you just want to do a single donation and don't want to wait until next month, you can also donate through paypal, to "frodo_gv@hotmail.com".

Also, if you find any non-translatable texts (other than error messages) feel free to tell me. It's possible some texts are not yet in the locale file.

**Comment by XuXinMing** [comment]
Okay, I have sent you $100 using PayPal

**Comment by Frodo45127** [comment]
Thanks again for the support! It's really appreciated.

As for this issue, as the translation is already in the repo and in the 2.0.2 release, I'll proceed to close it. Feel free to open a new one or do a pull request (whatever you find easier) if you have any update to the translation.
