### ISSUE TITLE
TSV extract no longer possible "Create Mass-Export TSV" no longer works

### ISSUE THREAD

**Issue by gdwitt** [Frodo45127/rpfm#119]
I was using this last month and RPFM vn 1.6.2 had a mass-export feature.
I could export all the db files as tsv and had an instant tsv folder to compare with another version of a mod.
This has been disabled with the current release.
I can now "extract", but I just get a mass of folders/directories, which makes diffing difficult.
I am using the Attila version.
Was this feature removed?

I notice that the EXTRACT feature on the right click menu works, but it just gives me binary db files that I can't use to compare.

That folder import features is amazing. Much better than PFM.
Patreon supporter here.

**Comment by Frodo45127** [comment]
About "Extract", means "extract this binary file". It's not intended and never was to extract tables as tsv. 

About the mass export feature, I just tested it and it works here. What does it do when you try it? It´s disabled on the menu? It fails with some error?

**Comment by gdwitt** [comment]
It is disabled in Attila with 2.0.2. It used to enable on right click when you opened up a pack and didn't dig into any directories. 
It's not an emergency. 
I can switch back to 1.6.2 to mass extract then back to 2.0.2 for the new features.

**Comment by Frodo45127** [comment]
Do you have your paths configured correctly in the preferences? That button is disabled if your game path is not configured correctly or you don't have schemas for the game.

**Comment by gdwitt** [comment]
Ok. That seems to fix the problem. I had it pointing to Total War Attila/data/. 
When I removed the data, I got the feature.
It says the schema are up to date.
I wonder why I got so many features working with the wrong path.
Thank you so much!

**Comment by Frodo45127** [comment]
np, always happy to help. As it is fixed, I'll close the issue.

**Comment by lampuiho** [comment]
I have the same problem. Should I create a new ticket? The folder path already points to the path with the exe not data. Mass-Import/Export as TSV buttons are still greyed out. Only the buttons for individual files when right clicking in the right hand panel works.
