### ISSUE TITLE
rpfm doesn't cope with malformed input

### ISSUE THREAD

**Issue by Trolldemorted** [Frodo45127/rpfm#12]
If you want to fix that within rpfm's pack module you have to
- stop trusting the sizes you read in the header
- ensure the payload-position variable does not overflow (twa_pack_lib uses [checked_add](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_add))
- enforce an opened file you lazily read from is not modified
- enforce `open_dependency_packfile` is using a valid file, or stop using unwrap() all the time

For the sake of simplicity, I'd also recommend you move all pack-related filesystem usage into the same module.

**Comment by Frodo45127** [comment]
This is closed, as #11 will overwrite most of the logic anyway.
