### ISSUE TITLE
Export as TSV reordering columns alphabetically.

### ISSUE THREAD

**Issue by GrouchPotato** [Frodo45127/rpfm#120]
The 'Export as TSV' reorders columns alphabetically in the exported file. Expected behaviour would be that the exported file retains the original table column ordering.

The issue is when trying to use an external application to manipulate data; having things out of order makes such work a bit more painful.

**Comment by Frodo45127** [comment]
Not a bug. That has been the default behavior of the export as TSV feature since... I wrote it. The order it exports is the order the columns have when they're encoded on the binary files. I have to use that order because if I use the visual one (the one you see in RPFM) you may move a column and suddenly the TSV that has the pre-move order is no longer valid for import.

**Comment by GrouchPotato** [comment]
Ah.... This makes some sense.

So the use-case problem I'm getting from this is that when working with an external spreadsheet, data imported / exported via TSV isn't in the same the same order as data copy/pasted directly. In my case I need to break tables down (units into those that are single unit entities and those that aren't as an example). I can work around the problem by exporting/importing each modified sub-table individually from sheets via TSV, but it'd be much easier if I could copy/paste data directly back in.

I could of course copy/paste the data out, but then I'd also have to manually enter the column headers. the TLDR; is that things would be easier if the copy/paste behaviour was compatible with the TSV export/import.

Out of curiosity, how are the default column orders determined in the RPFM UI? Making the assumption that the ordering comes from the schema files, would it be possible to use that same ordering for TSV export, given the table schema version and field names are stored in the exported TSV? Would you object to me turning this into a feature request, or is this one of those 'not worth the implementation complexity' kind of things?

**Comment by Frodo45127** [comment]
1. Making copy/paste and import/export compatible is not possible. Earlier versions of RPFM had it (copy copied in the table's real order) and it was quite a pain to work with.
2. For the default order, there is a "ca_order" value in each field in the schemas. If it's not -1, then that value it's used to determine what position the column should have. If it's -1 in all columns, we just put the key columns first. That value comes from the position of the column in the assembly kit, so we can have the same order, and we can then copy/paste to/from the assembly kit.
3. Mmmmm maybe those column names can be used indeed, though. That would also allow RPFM to maintain compatibility with tsv files exported before this..... Well, that's possible, and it shouldn't be too hard to implement... Another feature to implement when I have time or someone does it instead.

**Comment by GrouchPotato** [comment]
RE 1&2: Understood.

RE 3: Would you like me to close this and re-submit as a new feature request?

**Comment by Frodo45127** [comment]
Either that, or change the title of the issue to request that feature.
