### ISSUE TITLE
In DB table view, sorting or filtering with boolean fields does not work.

### ISSUE THREAD

**Issue by QuantumCatgirl** [Frodo45127/rpfm#121]
Sorry to keep spamming this issues board :-/

In a DB view, sorting data or using the table filter with a boolean field does nothing.

Steps to demonstrate:
- Open data.pack
- Go to db/main_units_tables/data__
- Click on the field header 'Unit Scaling' (or any other in-use boolean field)
--> The sorted ^ icon is shown in the column header, but no sorting is done.
- At the bottom in the filtering dialogue, select 'Unit Scaling'
- Try a variety of bool as string/int representations (I tried '1', 'true', 'TRUE', 'yes', 'YES')
--> No results

However...
- Now open the non-global search/replace dialogue with ctrl+F
- Select 'Unit Scaling' in the new bottom UI section.
- Enter one of 'true', 'TRUE','tRue', '1' ('yes' doesn't work, but who uses that?) in the Search Pattern field
--> Correct number of results shown next to the 'Close' button.

Anyhow..., On a more personal note I want to reiterate my thanks for maintaining this project. If I had to work with CA's assembly kit I think I'd go insane and spend the rest of my days rocking back and forth muttering something about XML formats. You've literally saved me from that :-D

**Comment by Frodo45127** [comment]
Known bug. Only search works on booleans for now. The fix is subclassing the filter and make it behave properly on those cases, which should come when I finally get the multicolumn filter working. And no problem. Reporting bugs here makes them easier to remember, so it's more possible I fix them at some point.

**Comment by Frodo45127** [comment]
Fixed a while ago. Closing for cleanup.
