### ISSUE TITLE
Provide option to show imagefiles at their original size (not stretched)

### ISSUE THREAD

**Issue by wolphyx** [Frodo45127/rpfm#124]
**Describe your problem**
As of now, opening imagefiles like eventpics in RPFM 2.0 causes them to be stretched to window size, with often pixellating results. It would be useful if one were able to toggle this behaviour and show them in original size instead, so one can actually judge what a skill icon looks like without exporting the whole UI folder first.

Ideally, RPFM should only fit the image to window size if otherwise it would exceed it.

**Extra info?**
Occurs in RPFM 2.0.2

**Comment by Frodo45127** [comment]
Fixed in develop branch. Now images are shown in their original size unless the window is smaller than them. In that case, they're resized to fit the window.
