### ISSUE TITLE
Failed to compile on Linux due to missing lib

### ISSUE THREAD

**Issue by KHN190** [Frodo45127/rpfm#125]
I tried to compile rpfm on Ubuntu 18.04 and failed on building `rfpm-ui`:

```bash
  = note: /usr/bin/ld: cannot find -lqt_subclasses
          collect2: error: ld returned 1 exit status
```

This is due to a missing lib `qt_subclasses`. Though I see the command using local `./libs` directory which contains a `qt_subclasses.lib`, I think `.lib` is not usable for Linux. Can I compile the `.so` myself using source code?

**Comment by Frodo45127** [comment]
qt_subclasses is compiled from the rpfm_ui/qt_subclasses folder when you compile rpfm_ui. If it's not finding it and you haven't touched the build.rs... maybe there was some error while compiling it? Do you have qt and qmake installed?

**Comment by KHN190** [comment]
@Frodo45127 I have Qt 5.13.0 built from source (tried 5.15 but it says can't recognize the version and is falling back to closest version 5.13), I also didn't edit source code yet, and for the all 285 building tasks it is the only error I have in compilation..

Does Qt version matter here? In doc and readme the numbers don't meet.

**Comment by KHN190** [comment]
Or if it's easier to add a compiled dylib for Linux under `./libs`?

**Comment by Frodo45127** [comment]
any version of qt above 5.8 is enough. You can check why it doesn't compile by compiling it manually. Just go to rpfm_ui/qt_subclasses, then launch qmake, then make. That's really what cargo does when compiling the UI.

**Comment by KHN190** [comment]
Thanks, that's helpful! I got the error:

```bash
$ qmake
Project ERROR: Unknown module(s) in QT: KTextEditor
```

Means kde framework missing? Tried install `libkf5texteditor-dev` and `libktexteditor4` but neither fix it.

**Comment by Madcliff** [comment]
I am getting this same error when trying to build on Arch...

**Comment by Frodo45127** [comment]
Here on arch, I just needed qt and the ktexteditor (kf5) package. If that doesn't work.... try compiling it with qt-creator. Sometimes that works. Sadly, this falls into the "weird c++ magic" category. Works as-is in some systems, needs modifications and dark rituals on others. And I have no idea why.

**Comment by KHN190** [comment]
I had some progress today building kf5 from source - the reason I think `libkf5texteditor-dev` doesn't work because my Qt is built from source, and here I had new kde framwork 5: `/usr/lib/x86_64-linux-gnu/*.so` including `libKF5TextEditor.so`.

However, when I enter `qt_subclasses` and manually do `qmake` I still got:

```bash
Project ERROR: Unknown module(s) in QT: KTextEditor
```

How do I link kf5 to this project (or, the Qt it is using)?

ps. This [guideline](http://www.linuxfromscratch.org/blfs/view/svn/kde/kf5-intro.html) builds the whole kf5, even though we don't actually need all of them but it's quite informative. Also [this post](https://github.com/n4n0GH/hello/issues/41) on GitHub helped.

Thanks!

**Comment by Frodo45127** [comment]
After checking a bit on my side, you may need the ktexteditor.pri file. On arch, it gets installed as part of the ktexteditor package, on `/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri`. Not sure where it gets installed in other distros, but it may be a clue to why KTextEditor it's not getting found. Also, I'm going to pin this issue, as it may be quite useful to others too in the future.

**Comment by KHN190** [comment]
Finally, got it running. :D For anyone who needs to build kf5 with Qt, have a look at the [gist](https://gist.github.com/KHN190/72d279aa62b225a7808e30e17fc77e35).

0. install Qt
1. download kf5 source code
2. in kf5 source code directory run `install.sh`
3. verify in `qt_subclass` dir with `qmake`
4. in rpfm run `cargo build`

**Comment by drage0** [comment]
on fedora 33, fixed by installing kf5-* and adding -I/usr/include/KF5/ to INCPATH in rpfm_ui/qt_subclasses/Makefile. (because /usr/include/KF5/KTextEditor/ktexteditor/editor.h includes <KSyntaxHighlighting/Theme>...)
i have also ran `make` inside rpfm_ui/qt_subclasses/ before running `cargo build` again.

**Comment by Frodo45127** [comment]
I got that one too on both arch and windows. The solution for me was to change <KSyntaxHighlighting/Theme> with <KF5/KSyntaxHighlighting/Theme> in editor.h and view.h.

**Comment by Madcliff** [comment]
This error is occurring again on the most recent PKGBUILD

**Comment by AaronBPaden** [comment]
@Frodo45127 Hiya, I have an alternative for Arch users.

0001-Add-include-for-Arch.patch
```
From 5d3a4c43eec2a3a42fcd3b75acf4737430448824 Mon Sep 17 00:00:00 2001
From: Aaron Paden <aaronbpaden@gmail.com>
Date: Mon, 5 Sep 2022 18:46:06 -0500
Subject: [PATCH] Add include for Arch

---
 rpfm_ui/qt_subclasses/qt_subclasses.pro | 1 +
 1 file changed, 1 insertion(+)

diff --git a/rpfm_ui/qt_subclasses/qt_subclasses.pro b/rpfm_ui/qt_subclasses/qt_subclasses.pro
index ca8e6925..a5a443de 100644
--- a/rpfm_ui/qt_subclasses/qt_subclasses.pro
+++ b/rpfm_ui/qt_subclasses/qt_subclasses.pro
@@ -89,6 +89,7 @@ debug:UI_DIR = debug/.ui
 unix {
 
     # For some reason, these flags fuck up compilation on windows, so we leave them linux only.
+    INCLUDEPATH += /usr/include/KF5/KSyntaxHighlighting
     QMAKE_CXXFLAGS = -Wl,-rpath='${ORIGIN}'
 }
 
-- 
2.37.3
```

We can add this patch to the PKGBUILD like this:

```
# Maintainer: Frodo45127 <frodo_gv@hotmail.com>
pkgname=('rpfm-git')
pkgver=3.0.14.2611.gfd33755d
pkgrel=1
pkgdesc="Rusted PackFile Manager (RPFM) is a modding tool for modern (since Empire) Total War games."
arch=('x86_64')
url="https://github.com/Frodo45127/rpfm.git"
license=('MIT')
depends=('qt5-base' 'qt5-imageformats' 'xz' 'p7zip')
makedepends=('git' 'rust' 'cmake')
provides=('rpfm')
source=("git+https://github.com/Frodo45127/rpfm.git"
"0001-Add-include-for-Arch.patch")
sha256sums=('SKIP'
            '64b335ea9f4652f2846316ea0883f6da44777cbb1dd62948690335526501841c')
_programname=('rpfm')

pkgver() {
    cd $_programname
    echo "$(grep '^version =' $srcdir/$_programname/rpfm_ui/Cargo.toml|cut -d\" -f2).$(git rev-list --count HEAD).g$(git rev-parse --short HEAD)"
}

prepare() {
    cd $_programname
    patch -p1 <"../0001-Add-include-for-Arch.patch"
}

build() {
    cd $_programname
    env CARGO_INCREMENTAL=0 cargo build --release
}

package() {

    # The executables.
    install -D -m755 "$srcdir/$_programname/target/release/rpfm_ui" "$pkgdir/usr/bin/rpfm_ui"
    install -D -m755 "$srcdir/$_programname/target/release/rpfm_cli" "$pkgdir/usr/bin/rpfm_cli"

    # The icons.
    mkdir -p "$pkgdir/usr/share/$_programname/icons"
    for image in "$srcdir/$_programname/icons/."; do
        cp -R $image "$pkgdir/usr/share/$_programname/icons/"
    done

    # The language files.
    mkdir -p "$pkgdir/usr/share/$_programname/locale"
    for locale in "$srcdir/$_programname/locale/."; do
        cp -R $locale "$pkgdir/usr/share/$_programname/locale/"
    done

    # The UI files.
    mkdir -p "$pkgdir/usr/share/$_programname/ui"
    for ui_template in "$srcdir/$_programname/rpfm_ui/ui_templates/."; do
        cp -R $ui_template "$pkgdir/usr/share/$_programname/ui/"
    done

    # Shortcuts.
    install -D -m644 "$srcdir/$_programname/install/arch/rpfm.desktop" "$pkgdir/usr/share/applications/rpfm.desktop"

    # License.
    install -D -m644 "$srcdir/$_programname/LICENSE" "$pkgdir/usr/share/licenses/$_programname/LICENSE"

    # This one is not in the qt5-imageformats package by default since Qt 5.8.
    #install -D -m644 "$srcdir/$_programname/imageformats/libqdds.so" "$pkgdir/usr/lib/qt/plugins/imageformats/libqdds.so"
}
```

This way we can avoid running sed on files owned by root.

**Comment by Frodo45127** [comment]
@AaronBPaden Been testing this in develop for a few days, and seems to work quite well. I've replaced the seds with the patch to the pro file for the next version.
