### ISSUE TITLE
VCRUNTIME140_1.dll was not found. Program cant launch, the dll is present in the system, program is unusable.

### ISSUE THREAD

**Issue by AstartesFanboy** [Frodo45127/rpfm#130]
**Describe your problem** Cant even launch the program, the program will give me an error message saying the dll isnt there when it clearly is. 

**Extra info?** v 2.1.1

**Comment by Frodo45127** [comment]
Fixed with 2.1.2. Don't know why the compiler started using that dll in the new pc.
