### ISSUE TITLE
version 2.1.3, a new terminal appears no matter what

### ISSUE THREAD

**Issue by MrHoon** [Frodo45127/rpfm#131]
**Describe your problem**

I updated to 2.1.3 and a new terminal now appears whenever you open the exe. No way to really close it down. I usually have a ton of RPFMs running and each terminal basically just kills my task bar space

If the terminal can't be removed, can there be an option to hide it somehow?

**Extra info?**

![terminal](https://user-images.githubusercontent.com/61536754/90471765-055be180-e0ed-11ea-81ab-fa2066cf7526.png)

**Comment by Frodo45127** [comment]
It's just the debug terminal. I forgot to disable it before the last hotfix (two hotfixes in the same day is not a good combination). Will recompile RPFM without it later today. For now, just ignore it.

**Comment by Frodo45127** [comment]
Fixed in 2.1.4
