### ISSUE TITLE
How to install the latest version?

### ISSUE THREAD

**Issue by prideyn** [Frodo45127/rpfm#133]
After downloading v2.15 and running rpfm-cli I get a message error saying that I'm missing vcruntime140.dll.

**Comment by Frodo45127** [comment]
I'll see if I can include it for the next release. For now, install vc_redist.x64.exe (from microsoft page). After that, it should work.

**Comment by prideyn** [comment]
Thank you very much for answering. I tried again and for some reason this time it worked.

**Comment by gdwitt** [comment]
I had to move the location of the prior version from its folder. I just drop the zip in my steam/common folder, unpack and then open pack with and browse the exe.

**Comment by Frodo45127** [comment]
Fixed in the last beta, that now includes that file.
