### ISSUE TITLE
DB Integrity - primary key constraint?

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#137]
At the moment we can insert rows with the same primary key.

in TWaD_%.xml files, primary key is designated as
```
<primary_key>1</primary_key>
<name>key</name>
```

Is there a way to add primary key constraint?

**Comment by Frodo45127** [comment]
RPFM already have that kind of constraint (the "key" columns are the same as in Dave) but it's not a hard constraint, but a soft one (you can put duplicate entries, but the Diagnostics tool will mark them as an error). So... I guess it's already done?

**Comment by Teddybear2020** [comment]
Yes, it's already done. I also mean to add color to indicate keys.
Is It Possible?
![image](https://user-images.githubusercontent.com/73296797/100160722-2dfc3000-2ec1-11eb-9502-bf62868e56f3.png)
