### ISSUE TITLE
Feature Request: MultiFilter like DAVE Visual Editor

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#138]
At the moment we can filter only by one Column.

can we get like this?
![image](https://user-images.githubusercontent.com/73296797/97056167-03048080-1591-11eb-86bb-c946fdeda96c.png)

**Comment by Frodo45127** [comment]
Already done in a couple weeks ago (it's in the latest beta if you want to test it, but beware of bugs). So... closing as done.
