### ISSUE TITLE
 when I pressed the button Replace Current/Replace All the program closed.

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#139]
**Describe your problem**
 when I pressed the button Replace Current/Replace All the program closed.

![image](https://user-images.githubusercontent.com/73296797/97872794-ad19a080-1d27-11eb-8b42-345a0635990e.png)

**Extra info?**
<!--- "What version of RPFM did you used?"

**Comment by Frodo45127** [comment]
Should be fixed in the recently released 2.3. Do you still reproduce it in that version?

**Comment by Frodo45127** [comment]
Ok, turns out it was a different crash. Should be fixed in 2.3.2 that's currently building.
