### ISSUE TITLE
The new update makes RPFM close when trying to open TW Arena files

### ISSUE THREAD

**Issue by Korgulltheexter** [Frodo45127/rpfm#140]
The most recent update doesn't allow opening files from Total War Arena. RPFM just closes and doens't show any error. Please fix this, Arena has  returned to China and new content will come from this game.

**Comment by Frodo45127** [comment]
Do you have a crash log? In RPFM, go to "Game selected/Open RPFM config folder" and check if there is any file in the error folder. I have an idea of what can cause a crash in arena, but don't have the game installed and would need the log to be sure it's what I think.

**Comment by Korgulltheexter** [comment]
I checked the folder and there are error reports. Also I tested today the RPFM and it opens the Arena files without any error, it's working as intended.

**Comment by Frodo45127** [comment]
Good, then I'll be closing this issue.
