### ISSUE TITLE
Search issue(update v2.3.2 problem)

### ISSUE THREAD

**Issue by NCISSky** [Frodo45127/rpfm#141]
v2.3.1 has two searching problem, first is sometime searching button not working, second is when I develop search result, it always auto resume.
![圖片](https://user-images.githubusercontent.com/73961703/98318371-712d5680-2019-11eb-923d-8cc2e643f048.png)
![圖片](https://user-images.githubusercontent.com/73961703/98318404-84402680-2019-11eb-8c1e-f80c6c8c270a.png)

7/11 update
now I cannot use search result to jump to the column

**Comment by Frodo45127** [comment]
The first one is a qt bug, triggered specially with the dark theme, which should be fixed with qt 5.15.2, when it reaches the repos. It can be mitigated a bit by using the light theme.

The second one should be fixed in the build I'm building right now.
