### ISSUE TITLE
Troubles with Building/Executing

### ISSUE THREAD

**Issue by databane** [Frodo45127/rpfm#143]
Building link doesn't work on front page.  I'm inexperienced in Rust, LOVE Warhammer 2, and wanted to give RPFM a go.

Older versions apparently included an executable, but couldn't find one in any of the most recent release files.  Apologies if I've overlooked something.

**Comment by Frodo45127** [comment]
Here is the correct link: https://frodo45127.github.io/rpfm/chapter_comp.html Have to find some time to fix it...

And I'm not sure what you meant with "Older versions apparently included an executable". The only exes in here are in the releases, not in the build intructions.

**Comment by databane** [comment]
In posts on Total War forums concerning older releases people indicated there was a .exe in the download.  I've looked at the v2.3.4 aip and have not found the .exe, so was looking for direction.

I asked about building because I have a separate interest in the implementation.
