### ISSUE TITLE
Search function request

### ISSUE THREAD

**Issue by ghost** [Frodo45127/rpfm#144]
It would be nice to have a search option to search inside all values in the current folder and subfolders. Currently I do this by unpacking it and using fileseek, which is not very efficient.

**Comment by Frodo45127** [comment]
Mmmmm I think I may need more context to fully understand your request.

**Comment by Teddybear2020** [comment]
It would also be helpful, if we can find all tables by key where it is used.
Currently I do this by searching key in xml files, here \assembly_kit\raw_data\db

**Comment by Frodo45127** [comment]
mmmm back to this one (I'm still on a bit of a coding break), I'm not sure what you guys mean. For Teddy, not sure if you mean searching on the schema (which is already done in the global search) or searching on data (which again, can be done in the global search). And for Gramble, the fact you mention "fileseek" makes me think you mean a way in code to search, which is already implemented via the numerous getters by path/type in the PackFile module, but still not sure if that's what you meant.

**Comment by Frodo45127** [comment]
Still waiting an answer for this. Not sure what was requested.
