### ISSUE TITLE
Make with Error E0599

### ISSUE THREAD

**Issue by psv-git** [Frodo45127/rpfm#147]
v.2.3.3, v.2.3.4
![Screenshot_08122020_230050](https://user-images.githubusercontent.com/31421240/101535418-a840b000-39a9-11eb-8f58-4d30e0464111.png)

**Comment by Frodo45127** [comment]
Here it builds correctly on both, stable and nightly. What version of Rust and OS are you trying to compile to?

**Comment by psv-git** [comment]
Debian 10
Rust 1.41.1

I see on screenshot "f32::MAX", not "std::f32::MAX". Is it correct?

**Comment by psv-git** [comment]
std::<type>::<const>  solved the problem

**Comment by psv-git** [comment]
also
![Screenshot_09122020_172934](https://user-images.githubusercontent.com/31421240/101642692-55680680-3a44-11eb-9530-0390d4b5b9b9.png)
