### ISSUE TITLE
cdir_events_dilemma_choice_details_tables decoding error

### ISSUE THREAD

**Issue by dean-sullivan** [Frodo45127/rpfm#148]
**Describe your problem**

Trying to open the table cdir_events_dilemma_choice_details_tables in Total War Warhammer 2 I get the message "Error while trying to decode the DB table. There is no definition for this specific version of the table in the schema." RFPM is 100% set to the correct game in preferences.

**Extra [info?**]

RPFM v 2.3.4

![image](https://user-images.githubusercontent.com/62270333/102177952-162a3180-3eec-11eb-8e5e-5b3fa9b2836a.png)

**Comment by Frodo45127** [comment]
Make sure your schemas are up-to-date, as that table is one of the ones that need the latest schema  to be decoded.

**Comment by dean-sullivan** [comment]
Updating the schemas didn't work. Deleted rpfm and re-downloaded it did the trick. Cheers.
