### ISSUE TITLE
land_units_additional_personalities_groups_junctions_tables

### ISSUE THREAD

**Issue by Sanatyr** [Frodo45127/rpfm#149]
The current schema is showing an error (in the diagnostics window) regarding missing references to "key" from "land_units_additional_personalities_groups" table, when, afaik, the table used by the game is "land_units_additional_personalities_groups**_junctions**_tables" and the column is "group".
I know there is a table called land_units_additional_personalities_groups in DAVE, but does it do anything considering modders can add new personalities without it? Maybe it should be classified as a warning not an error.

Edit: This is about Warhammer 2

**Comment by Frodo45127** [comment]
You can configure an exception from diagnostics for that table (check the "PackFile Settings" section in the manual). It's not technically a bug, just that that specific reference does not really need the source data. And as the reference data is automatically recovered from Dave.... sure, I can patch it, but It's going to popup again in the next update. And I don't like hardcoding this kind of stuff. So for now it'll stay.
