### ISSUE TITLE
Land_units_tables

### ISSUE THREAD

**Issue by DeltaOfWar** [Frodo45127/rpfm#150]
Popping up of not being in the right game, but have tried on other files & were working properly.

noticed that where it says cached type says " Not Yet Cached" but others say DB.
I'm fairly new to this & this issue is also happening with PFM as well. 

It's for Total War Warhammer 2

**Comment by RodasPacco** [comment]
for me show undecoded packedfile in Total War Warhammer 2

**Comment by Frodo45127** [comment]
Try the latest beta from today. There were quite a few bugs in the schema updater that caused these problems, and the last ones should be fixed in that beta.
