### ISSUE TITLE
OR-Filter

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#153]
Hey, Thank you for your work, @Frodo45127 

Can you add OR-filter?

![image](https://user-images.githubusercontent.com/73296797/107232767-dd619100-6a32-11eb-8366-8af3581d4f73.png)

![image](https://user-images.githubusercontent.com/73296797/107232997-274a7700-6a33-11eb-9541-a1a9902f0ae8.png)

**Comment by Frodo45127** [comment]
It's on the list of stuff to add once I get to do another pass at the table filters, together with a "accept empty cells by default" option.

**Comment by Teddybear2020** [comment]
> It's on the list of stuff to add once I get to do another pass at the table filters, together with a "accept empty cells by default" option.

btw, how to filter by Boolean Field? (true/false)?

**Comment by Frodo45127** [comment]
yeah, the bug that caused boolean columns to not work with sorting/filtering was fixed a while ago, so now "true" or "false" should work for filtering boolean columns. Or at least I remember fixing the sorting, and I think the filtering one was fixed with it.

**Comment by Teddybear2020** [comment]
> yeah, the bug that caused boolean columns to not work with sorting/filtering was fixed a while ago, so now "true" or "false" should work for filtering boolean columns. Or at least I remember fixing the sorting, and I think the filtering one was fixed with it.

I created Issue but it was deleted (or where did my topic disappear?) where I provided image which show that sorting boolean columns do not work. 

Can you check it?

**Comment by Frodo45127** [comment]
If you mean this one (https://github.com/Frodo45127/rpfm/issues/155) is closed, as it's already fixed in develop, and you can test it in the latest beta.

**Comment by Frodo45127** [comment]
Closing, as it has just been implemented in the dev branch through the use of filter groups.
