### ISSUE TITLE
Boolean Filter doesnt work

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#155]
hey!

I did some tests.

![image](https://user-images.githubusercontent.com/73296797/107760769-5b77ad80-6d3b-11eb-9454-86d2066bbfa1.png)

![image](https://user-images.githubusercontent.com/73296797/107760819-6d595080-6d3b-11eb-83a6-8c21769641cb.png)

![image](https://user-images.githubusercontent.com/73296797/107760866-819d4d80-6d3b-11eb-94f2-d6aaa6fa3878.png)
false or False or 0 or 1 do not work

**Comment by Frodo45127** [comment]
Indeed, after checking the code it seems I only applied the boolean column fix to sorting, not filtering. Got a patch that seems to work almost done, so it should be done later today.

**Comment by Frodo45127** [comment]
Fixed on develop branch, so it should be in the next beta/release.
