### ISSUE TITLE
Definite Memory Leak

### ISSUE THREAD

**Issue by JosephHubbard** [Frodo45127/rpfm#156]
This program contains a definite memory leak (or potentially a malware script).
After using this program my C: drive filled up instantly. After hours of trying to debug why my hard drive seemed to be filling itself up with unremovable fragments I narrowed it down to the AppData folders for rpfm taking up all of the avaiable space on its drive instantly, regardless of if you have just freshly started the computer or not.
I would not recommend using this program until this issue is sorted.

**Comment by Frodo45127** [comment]
First, a memory leak doesn't fill a hard disk, but the ram memory...
Second, RPFM has an "autosave" feature, that saves your packfile to a folder inside appdata every few minutes (configurable in the settings). RPFM stores the last 10 autosaves (configurable in the settings too in recent betas). Maybe you opened pretty big packfiles for a while and RPFM saved them?
