### ISSUE TITLE
Undecoded PackedFIle

### ISSUE THREAD

**Issue by Starwarsbeta1** [Frodo45127/rpfm#157]
Trying to follow your guide on adding custom unit into Warhammer 2 got this when trying to make the first land_unit table. This is my first time modding Warhammer and using rpfm so maybe I'm just doing something wrong, but the error says it is a bug and to report it so that is what I'm doing. I should be on whatever the latest version is. 2.3.4 I think?

![Capture](https://user-images.githubusercontent.com/79424723/108640679-5a8bfd80-7458-11eb-8c45-b370a777fa56.PNG)

**Comment by Frodo45127** [comment]
It's a known bug in 2.3.4. If you can, try switching to the beta update channel and test the latest beta, as the most common cause of this bug is fixed there.

**Comment by Starwarsbeta1** [comment]
tried the 2.3.103 beta and it didn't work at first but after reloading the program and clearing and updating the schema about 4 times, it is now working.

**Comment by Frodo45127** [comment]
Closing this as the cases I found of this happening are fixed in 2.4.
