### ISSUE TITLE
Math operations on Integer columns are not rounded

### ISSUE THREAD

**Issue by Jackless89** [Frodo45127/rpfm#160]
When doing a math operation on Integer dolumns and the result would be a decimal the result isnt rounded to the next valid Integer it is just doing nothing for that particular cell.

**Comment by Frodo45127** [comment]
What RPFM version do you have? I just tested in 2.4.1 and it's rounding up the values.

**Comment by Jackless89** [comment]
Yes im sorry, I have just upgraded and everything is working as expected. Thank you very much ;)
