### ISSUE TITLE
Update Issue

### ISSUE THREAD

**Issue by databane** [Frodo45127/rpfm#161]
Having difficulties updating; get following possible errors in message:

"It's a file in the data folder of Warhammer 2 and you haven't close the Assembly Kit."
"You don't have permission to read/write the file in question."

I have nothing open, and there has been no change in permission I'm aware of.  What could it be?  Essentially, I'm surprised because haven't had issues with prior updates

**Comment by Frodo45127** [comment]
That's the not so correct message for "permission denied". It means RPFM can't download and unpack the update to RPFM's folder because windows doesn't let it write in that folder. Make sure you can write files there (or move RPFM to another place where you can create/delete files, and try again.

**Comment by Xiaaaaaaaaaa** [comment]
I've got this issue when I tried to update.

![Untitled](https://user-images.githubusercontent.com/81507930/112746533-8b240180-8fd9-11eb-9647-6b6ef17e3088.jpg)

**Comment by Frodo45127** [comment]
What RPFM version do you have? If it's too old, that message is normal. RPFM update checker in older versions broke with the new updater introduced in... v2.1 I think.

**Comment by Xiaaaaaaaaaa** [comment]
Can you post an URL link for me to update it? I couldn’t do it via the program.
