### ISSUE TITLE
When sorting, erroneous deletion of an unselected cell

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#162]
if we sort by column then we cant del value in cell

Example:
sort by Building
![image](https://user-images.githubusercontent.com/73296797/112758566-c59c9700-8ff7-11eb-98f8-eb61c5c023a4.png)

when I want to del value "wh_dlc06_dwf_art_bolt_thrower_0" in Unit Column another cell is deleted instead.

![image](https://user-images.githubusercontent.com/73296797/112758667-275d0100-8ff8-11eb-9d49-a4567584447e.png)

**Comment by Frodo45127** [comment]
Thanks for the report! Just checked it, reproduced it (another case of "delete visual index instead of logic one"), and fixed it on the develop branch. Should come with the next beta update.
