### ISSUE TITLE
Interface enhancements: Create DB

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#163]
may I ask you to consider setting the number of tables when creating?

![image](https://user-images.githubusercontent.com/73296797/115530840-cf36b900-a29c-11eb-8197-6263fa959538.png)

**Comment by Teddybear2020** [comment]
this is useful when creating different tables for different factions, races or by type of effect.  although in the final version of the mod it will all be combined, but it helps when editing, for example, effects for a specific faction.

**Comment by Frodo45127** [comment]
Doesn't the new queek file feature works better for that situation?

**Comment by Teddybear2020** [comment]
> Doesn't the new queek file feature works better for that situation?

if I need to create 20 DBs, then every time I create I need to set a new name and each time an input window appears.
the new function only eliminates the input of the table name, but I still need to add 20 times to the end of the name of the number 1,2,3,4, etc. so that there are no duplicates.

![image](https://user-images.githubusercontent.com/73296797/115634733-d8fb0380-a312-11eb-8097-1341277f17b1.png)

**Comment by Teddybear2020** [comment]
if the interface allows you to add an item to the list, isn't it smart to add the number of repetitions for that item?

**Comment by Teddybear2020** [comment]
(sorry for Google Translate)
