### ISSUE TITLE
Problem with new three kingdoms models

### ISSUE THREAD

**Issue by Kiwipea** [Frodo45127/rpfm#164]
I'm trying to extract the new models and bring them into another program 

However all the new ones released with three kingdoms newest update appear to be broken regardless of which program i bring them into, All the old models work fine, its only the fates divide characters that break

![Capture](https://user-images.githubusercontent.com/83354806/116417100-f9dac180-a808-11eb-8f93-6ef28d595fd1.PNG)

Any help would be much appreciated because this is really frustrating

**Comment by Frodo45127** [comment]
This looks more like an issue in the tool you're using to open the models than an issue in RPFM, as RPFM extracts the data as-is. It doesn't perform any changes to rigidmodel if you haven't open them before extracting them. Probably those models use a slightly different format that confuse the tool. Ask the author/s of the tool you're using to check it in their tool.

**Comment by Kiwipea** [comment]
Thanks!
