### ISSUE TITLE
Cannot Create DB Files

### ISSUE THREAD

**Issue by jdcon83** [Frodo45127/rpfm#168]
I just updated to 2.5 yesterday (6/18). After updating, I can no longer simply create a DB file in a mod by right-clicking. 

![dbfile](https://user-images.githubusercontent.com/86157144/122644426-b7cc4e80-d0da-11eb-9580-72a8d71345df.png)

**Comment by Frodo45127** [comment]
You need to generate the dependencies cache for that to work.
