### ISSUE TITLE
non-library projects should include Cargo.lock for reproducible builds

### ISSUE THREAD

**Issue by Trolldemorted** [Frodo45127/rpfm#17]
[Otherwise a yanked (or non-backwards compatibly updated) (recursive) dependency will break builds on new git checkouts](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries)

**Comment by Frodo45127** [comment]
In my defense I'll say when I started with cargo, the first thing I saw about "cargo.lock" was that it was for some internal stuff and it could be ignored. Never saw that page until today. Anyway, it's in develop now. It'll be in master when the next release gets published.
