### ISSUE TITLE
Troy VFX Mods Using PFH6 Crashing/Not Loading

### ISSUE THREAD

**Issue by vahndaar** [Frodo45127/rpfm#170]
I have a mod which makes changes to a few vfx xml files. Using PFH5 the file loads up in Troy and works fine. However, when saving as PFH6 the mod either crashes the game on launch or simply doesn't apply the mod even when selected from the mod list.

I've tested this with changing the pack file to various types. Historically this type of mod would be set to the Movie type so that the game applies the vfx changes. Doing so causes a crash at launch with PFH6.

Changing the mod to the Mod type or other types allows the game to load but the mod changes aren't applied.

The only thing that currently works is by using the previous version PFH5.

I'm not sure if the issue is due to RPFM or the way the game handles the new headers. I suspect the latter.

**Comment by Frodo45127** [comment]
RPFM encodes the files correctly, I can assure you that. Or at least, correctly as the spec CA released. What I'm not sure is that the game expects non-mod PackFiles to have the new format. I'll take a look at it next week (don't have the game installed right now) and maybe add a format exception for Troy.

**Comment by Frodo45127** [comment]
Closing as, after the Game Selected rework I landed today, RPFM should now mark movie files for troy as PFH5, effectively fixing this.
