### ISSUE TITLE
Error: Table name ends in number

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#172]
Hi,

Steps:

1. Create new mod
2. add table campaign_difficulty_handicap_effects_tables
3. add data unknown1
4. got error
![image](https://user-images.githubusercontent.com/73296797/125690036-705907ee-a7c6-402c-959a-f3855ac93ad1.png)
5. rename unknown_a
6. Error still exists
7. double click on error row
![image](https://user-images.githubusercontent.com/73296797/125690159-caf475d9-8099-4f31-9166-dd224b8c8fcf.png)

If reopen mod file - its ok. no error.

**Comment by Frodo45127** [comment]
Not an issue. For performance and stability reasons, the diagnostics results are only updated on opening PackFile (if enabled in the settings), on table editing (if enabled in the settings) or when clicking one of the check buttons. You renamed a file, making the diagnostic that referenced it fail to find the old file. Next time, hit the check packfile again to update the results.
