### ISSUE TITLE
Error: Possibly outdated table

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#173]
Hi,

in my mod:
![image](https://user-images.githubusercontent.com/73296797/125690716-84bbc217-39f2-4d94-87d3-25af043f2edc.png)
![image](https://user-images.githubusercontent.com/73296797/125690759-0dff53b9-972b-467a-985d-903af8e9b8bb.png)

in CA data.pack
![image](https://user-images.githubusercontent.com/73296797/125690814-6f8a6fee-26a7-4905-8a9e-d56c0e2b2524.png)

Can you help with that?

**Comment by Frodo45127** [comment]
Hover over the error and it'll tell you what to do.

**Comment by Teddybear2020** [comment]
> Hover over the error and it'll tell you what to do.

![image](https://user-images.githubusercontent.com/73296797/125779124-4f7ae54c-2a20-454e-a7ac-38916d5c6c8f.png)

**Comment by Teddybear2020** [comment]
if I recreate db and then copy rows from db (where was the error) to new db - it is ok. 
why?

**Comment by Frodo45127** [comment]
.... did you read that tooltip? It explains why the error appeared in the first place, why the new table you created does not give an error, and how to fix your old table so you don't have to create a new table. Though now that I read it, the wording may need a fix on the first paragrahp.
