### ISSUE TITLE
db tables not opening.

### ISSUE THREAD

**Issue by luclib** [Frodo45127/rpfm#174]
Hi,

I installed the latest release of RPFM, version 2.5.3, and set it up to mod Warhammer II but I am encountering problems opening certain tables, especially the land_units_tables.

Whenever I double click the data_ file, I get the following error message: 
**'Error while trying to decode the DB Table: There is no Table Definition for this specific version of the table in the Schema.'**

I then click the 'Check Update Schema' in the Tab bar and received this error: 
**'Error while checking new updates :(

If you see this message, there has been a problem with your connection to the Github.com server. Please, make sure you can access to https://api.github.com and try again.'**

Finally, I tried the 'Check Updates' option and receive the following:
**'Error while checking new updates

There has been a problem when getting the latest released version number, or the current version number. That means I fucked up the last release title. If you see this, please report it here:
https://github.com/Frodo45127/rpfm/issues'**

Consequently, I found myself here.

**Comment by Frodo45127** [comment]
Either your firewall or your AV are blocking RPFM from talking to github to download the schemas or check for updates. Make sure RPFM has access through your firewall and that your AV is not blocking RPFM.

**Comment by luclib** [comment]
Thanks, I'll try that.

**Comment by luclib** [comment]
Hey, I tried your suggestion and it was working for a while but the problem's returned.

I allowed the app (rpfm.exe) access through the Windows firewall and I have had no indication that my AV was blocking the app. I have excluded it from my AV monitoring but that's where I am stuck right now.

**Comment by luclib** [comment]
At this point, it seems that sometimes it'll open a certain table and other times not.

**Comment by Orochi328** [comment]
Hello, Troy's DB is missing, can you update it? Thank you very much!

**Comment by Frodo45127** [comment]
Troy's schemas have been up-to-date since the day the mythos patch landed. Please, update your schemas. Also, I'll close this issue, as it seems the original issue was not from RPFM but some external program (AV?) causing issues, and no more info was provided.
