### ISSUE TITLE
RPFM Beta CEOs issue  (Three Kingdoms)

### ISSUE THREAD

**Issue by Ironictw2st** [Frodo45127/rpfm#177]
I am using the v2.5.106 beta release, I was testing it out and an important number values are missing here, both negative and 3 digits numbers are not present, meaning you can not give out discounts for upkeep you can only increase the upkeep. 

The only work around for not having the values is not touching their effect bundles thing in CEOs.

**Comment by Frodo45127** [comment]
Fixed for 2.6.2.
