### ISSUE TITLE
Schema missing `campaign_maps` table definition

### ISSUE THREAD

**Issue by abrthel** [Frodo45127/rpfm#19]
Schema definition is missing for `campaign_maps_tables` in warhammer schema

RPFM v1.2.0 with latest schema updates and I also verified that it's missing in the master branch.

**edit:**  *realized I forgot to mention which schema though I'm unsure if older games implemented the table*

**Comment by Frodo45127** [comment]
That table is not in the data.pack, and exporting it from Dave doesn´t generate the table file to include it in a PackFile. Are you sure that table can be exported somehow to a table file?

**Comment by abrthel** [comment]
I could very well be wrong, I just assumed if there was a DAVE raw_data xml file for the table then there would be a corresponding table in the data.pack.

There are a number of foreign key references to the table and it's where id's such as `warhammer_map_1` are created suggesting it is a used table. An example of a table that references `campaign_maps` would be the campaign_map column in `campaign_map_regions`. However if you can't export it then I'm not sure what's going in there.

Apologies for not being more helpful. I haven't poked around the pack files too much and have preferred to poke around the assembly kit raw data (xml) files.

**Comment by Frodo45127** [comment]
The fact that there is an xml file doesn't mean you can export a table. For example, all the "star_pos_xxx" tables are actually not exportable. They are used to generate the starpos file. If you want to check if a table is exportable or not, just try to export it and see if a binary file has appeared in "/working_data/db/table_name/tables/".

Anyway, I'll close the issue, but feel free to ask if you have any more doubts about it.
