### ISSUE TITLE
RPFM 3.0

### ISSUE THREAD

**Issue by mextrinc** [Frodo45127/rpfm#192]
Hi,

Ver: 3.0
Game: WH3

Problem: 

After changing values & saving (not string, just integers) in data.pack > db > melee_weapons I encountered an error:

Error while trying to save the currently open PackFIle:
Error while trying to save a row from a table: 
We expected a field of type "StringU8", but we got a field of type "l32".

**Comment by Frodo45127** [comment]
Have you fully restarted RPFM after both, the update and the schema update?

**Comment by mextrinc** [comment]
> Have you fully restarted RPFM after both, the update and the schema update?

I downloaded the release, opened it, it asked for a schema update so I did. 
After doing that, I went ahead and change some values and save, the error appeared. I restarted RPFM, changed the game, did the same thing yadayada. Error still there.

**Comment by Frodo45127** [comment]
mmmm not getting the error here with 3.0 and the schemas updated, and that table doesn't have any special features in the definition like grouping or bitwise, that can cause that....

**Comment by mextrinc** [comment]
Hm... that's really weird. 

I tried restarting my PC as well. Maybe I'll redownload the release and try again!

**Comment by Frodo45127** [comment]
Ok, now I see it. It's not the melee_weapons table, it's another table within the data pack that's failing to save.... well, at least the error message to not corrupt packs works. I'll see if I can find what table is causing it....

**Comment by mextrinc** [comment]
> Ok, now I see it. It's not the melee_weapons table, it's another table within the data pack that's failing to save.... well, at least the error message to not corrupt packs works. I'll see if I can find what table is causing it....

Thank goodness, always the hero to save the day.

I'll patiently wait as you find the table, thank you as always.

**Comment by ahamm3rs** [comment]
> 

I tried it pretty vanilla - just opened data.pack and tried to save it. Same error as mextrinc
"Error while trying to save the currently open PackFIle:
Error while trying to save a row from a table:
We expected a field of type "StringU8", but we got a field of type "l32"."

**Comment by Frodo45127** [comment]
Found the problem, there's a specific table that has a duplicate name, and that causes RPFM to get confuse about the type of the column.... not hard to fix.

**Comment by ahamm3rs** [comment]
> Found the problem, there's a specific table that has a duplicate name, and that causes RPFM to get confuse about the type of the column.... not hard to fix.

You rock :D

**Comment by Frodo45127** [comment]
Building 3.0.1 with the hotfix. So.... closing this issue.
