### ISSUE TITLE
.pack files

### ISSUE THREAD

**Issue by mextrinc** [Frodo45127/rpfm#194]
Hi,

Am I doing it wrong if I am just editing the base files for modding usage just like pre-3.0 RPFM? I tried the tutorials on usage of script.txt but that didn't work out so well, i'm not so sure..

edit: still crashes if i use the first method. which is, to edit base files

**Comment by Paterman93** [comment]
Same here. I have updated to 3.02 as well as switched the packfile from release to mod and back (was suggested on the 3.01 issue thread) Any changes to the data.pack on Total War Warhammer III result in the game crashing. Even edits that were working fine pre 3.00.

**Comment by Vavohu** [comment]
Same. I to gad mods working pre 3.0 that now cause crash.
Simply loading, changing nothing and saving the pack file still causes game crash

**Comment by tangmac0323** [comment]
crashed on starting for me, when the pack file only contains modification in _kv_rules_table

**Comment by Vavohu** [comment]
That isn't working for me. tried several different changes separately including script

**Comment by Frodo45127** [comment]
Should be fixed in 3.0.3. There was an error in the encoding/decoding of colour columns that caused 2 entries in the factions and battle_set_piece_armies tables to encode incorrectly, breaking 2 tables. Apart of that, it seems the packfile saved by RPFM is exactly the same as the original data.
