### ISSUE TITLE
New RPFM version causes the game to crash on launch.

### ISSUE THREAD

**Issue by budgetmodder** [Frodo45127/rpfm#196]
**Describe your problem**

Editing anything or even just opening and saving with no edits Warhammer 3 data.pack causes the game to crash on launch without even reaching main menu.

**Extra info?**

v3.0.3
This problem exists only in the new version with WH3 support. I can use v2.6.6 to do lua edits and the game works just fine but obviously there are no schemas to edit wh3 tables in that version. Something goes wrong with the saving process in current version.

**Comment by derpinsk** [comment]
@budgetmodder 

https://github.com/Frodo45127/rpfm/issues/195#issuecomment-1055263245

**Comment by budgetmodder** [comment]
I tried deleting appdata and validating steam files but the crashes still happened. Today I tried again and it worked so maybe it was steam messing something up with validation process.
