### ISSUE TITLE
v 3.0.4 crushed upon starting

### ISSUE THREAD

**Issue by tangmac0323** [Frodo45127/rpfm#197]
The program crushed right after starting after update from 3.0.3 to 3.0.4, non-action was taken except starting the app

**Comment by Frodo45127** [comment]
It seems to be a problem with a dependency that got updated today. I'm preparing a hotfix with the dependency reverted.

**Comment by Frodo45127** [comment]
Should be fixed in 3.0.5 (at least it didn't crash here). If you downloaded 3.0.4, manually download 3.0.5 and extract it over 3.0.4's folder. That should replace all the files properly with 3.0.5 ones.

**Comment by tangmac0323** [comment]
> It seems to be a problem with a dependency that got updated today. I'm preparing a hotfix with the dependency reverted.

thank you sir !
