### ISSUE TITLE
Warhammer: effects.description missing

### ISSUE THREAD

**Issue by Idrinth** [Frodo45127/rpfm#199]
**Describe your problem**
For Total War: Warhammer, the description column is missing in the effects_tables

**Extra info?**
Version 3.0.5
![grafik](https://user-images.githubusercontent.com/7874631/159425528-85c78a1f-a65a-4e3e-97b6-04320fb28968.png)
![grafik](https://user-images.githubusercontent.com/7874631/159425609-52c23393-7b20-41cd-8b16-bcfdcee1249e.png)

**Comment by Frodo45127** [comment]
Not a bug. Some columns like that one are removed from the table and turned into loc entries when exporting the table on Dave, so they're not in the exported table. So RPFM cannot load what it's not there.
