### ISSUE TITLE
Warhammer I support

### ISSUE THREAD

**Issue by Arsakes** [Frodo45127/rpfm#2]
What do I need to support warhammer I?
is it a matter of new json schema?

**Comment by Frodo45127** [comment]
For Warhammer I (and other games) It needs to be done:
- [x] Code to support different default folders for different games.
- [ ] An UI button to allow to change between games (to change the default path and stuff like that).
- [ ] Change the way the schema for db tables is loaded, as right now it's hardcoded to only load the one for Warhammer 2.
- [ ] Make an schema for Warhammer 1 tables.

That's more or less the esential stuff. 1 is more or less done, 2 and three will be done soon. 4... will take some time.

**Comment by Arsakes** [comment]
I can try do 4, I don't know rust, but for this i thinkg Conversion from PFM xml schemas to Json would suffice. What you think?
Also saving into pfm is more important than loading (you can just load extracted folder).

**Comment by Frodo45127** [comment]
XML to JSON wouldn't work, as RPFM schemas holds different data than PFM schemas, and PFM schemas are all (for all supported game) stored into 1 single file, while RPFM uses one for every game. Also, what do you mean with "saving into pfm is more important than loading (you can just load extracted folder)."?

**Comment by Arsakes** [comment]
Hmm I seen that  data were different for PFM, you have this masterfile and "selector" files that pick the version of each schema. I still think that combining info from all xmls you could get the json.
Second part you can ignore:)

**Comment by Frodo45127** [comment]
Sorry for taking too long to answer. About the schema, as Warhammer 1 and 2 are not too different (in table schemas) one thing we can do is use the one from Warhammer 2 as a base. I'm not sure how many tables would need to be fixed, but with that we can reduce the time needed to decode it by a lot (took me 8 days to get the entire Warhammer 2 schema working with no unknown columns, this should reduce it to less than 4).

But to be able to do it, I need to do some internal changes first, as you can't even load a schema of another game right now and there are some problems with the decoding UI in Windows I need to fix first. If you still want to help, I can contact you once all this stuff is done.

**Comment by Frodo45127** [comment]
Finally implemented in 0.6.0 release, so this is finally done.
