### ISSUE TITLE
PKGBUILD doesn't work as-is

### ISSUE THREAD

**Issue by Star-X555** [Frodo45127/rpfm#207]
**Describe your problem**
The PKGBUILD for Arch doesn't work.  It spits out this error right as it's working on rpfm-ui:

> error: linking with `cc` failed: exit status: 1
>   |
>   = note: "cc" "-m64" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/deps/rpfm_ui-9a68f50c954ac1ed.rpfm_ui.a84536be-cgu.8.rcgu.o" "-Wl,--as-needed" "-L" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/deps" "-L" "./libs" "-L" "/usr/lib" "-L" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/build/qt_core-49136a21296479ee/out/c_lib_install" "-L" "/usr/lib" "-L" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/build/qt_gui-ef9bc8da74b56849/out/c_lib_install" "-L" "/usr/lib" "-L" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/build/qt_ui_tools-93ae252d1028f245/out/c_lib_install" "-L" "/usr/lib" "-L" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/build/qt_widgets-4d4abcb84a00e932/out/c_lib_install" "-L" "/usr/lib" "-L" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/build/libssh2-sys-df0c376564938515/out/build" "-L" "/usr/lib" "-L" "./libs" "-L" "/usr/lib" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-lqt_subclasses" "-lKF5TextEditor" "-lKF5WidgetsAddons" "-lKF5XmlGui" "-lKF5IconThemes" "-Wl,-Bstatic" "/tmp/rustc8jnp56/libqt_ui_tools-48655bb185c1e6da.rlib" "/tmp/rustc8jnp56/liblibssh2_sys-e6a66627104cd460.rlib" "/tmp/rustc8jnp56/libqt_widgets-7586019840aae0e1.rlib" "/tmp/rustc8jnp56/libqt_gui-86bf05e1bd110eab.rlib" "/tmp/rustc8jnp56/libqt_core-afb113dde201c6e7.rlib" "-Wl,--start-group" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-6b2c1396410cc3a8.rlib" "-Wl,-Bdynamic" "-lQt5UiTools" "-lQt5Core" "-lQt5Gui" "-lQt5Widgets" "-lstdc++" "-llzma" "-lbz2" "-lgit2" "-lz" "-lssl" "-lcrypto" "-lQt5Widgets" "-lQt5Core" "-lQt5Gui" "-lstdc++" "-lQt5Gui" "-lQt5Core" "-lstdc++" "-lQt5Core" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/starx555/Downloads/rpfm-git/src/rpfm/target/release/deps/rpfm_ui-9a68f50c954ac1ed" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
>  = note: /usr/bin/ld: cannot find -lqt_subclasses: No such file or directory
 >         collect2: error: ld returned 1 exit status
>          
>
> warning: `rpfm_ui` (bin "rpfm_ui") generated 30 warnings
> error: could not compile `rpfm_ui` due to previous error; 30 warnings emitted
> ==> ERROR: A failure occurred in build().
 >    Aborting...

**Extra info?**
Yes, I did the editor.h and info.h fixes, it still spits out lqt_submodules errors.

**Comment by DavidTagt** [comment]
Have the same problem. I compiled with cargo however.

First error: 
[error1-2022-06-30.txt](https://github.com/Frodo45127/rpfm/files/9015259/error1-2022-06-30.txt)

That's when I checked this issue.

Ran qmake and make in "rpfm_ui/qt_subclasses". Got this error:
[error-qmake-2022-06-30.txt](https://github.com/Frodo45127/rpfm/files/9015168/error-qmake-2022-06-30.txt)

So I had only changed the `#includes` in editor.h, and not in view.h.
changed that to `#include <KSyntaxHighlighting/Theme>` in view.h

Ran `cargo build` again, but got the same error:
[error2-2022-06-30.txt](https://github.com/Frodo45127/rpfm/files/9015172/error2-2022-06-30.txt)

So I deleted that folder with rpfm and built again in a fresh one. Same error:
[error3-2022-06-30.txt](https://github.com/Frodo45127/rpfm/files/9015225/error3-2022-06-30.txt)

Reran with makepkg but yeah, same error. Took 9 min and 30 seconds though!
[error4-2022-06-30.txt](https://github.com/Frodo45127/rpfm/files/9015358/error4-2022-06-30.txt)

And here we are. Any ideas boss?

**Comment by Countdown24** [comment]
Hi, had the same issue. Got it to build by changing #include in editor.h and view.h to:

`#include </usr/include/KF5/KSyntaxHighlighting/KSyntaxHighlighting/Theme>`

Not an expert with this. Just tried something out and this worked for me.

**Comment by DavidTagt** [comment]
Uh yeah, that did the trick!

**Comment by Frodo45127** [comment]
Fixed (and got confirmation from others too) on the master branch. Thanks everyone for reminding me about this.
