### ISSUE TITLE
Calculated fields don't round to two decimals

### ISSUE THREAD

**Issue by gdwitt** [Frodo45127/rpfm#208]
I extracted all db files using create mass export from data.pack for Attila.  I did this about 1 month ago to the exact same data.pack.
I compared the tables using WinMerge.
There are significant apparent differences in the numbers in several tables, esp. Campaign Variables. 
About 5% of the fields now have 8 digit decimals which is a problem could create multiple problems.
I request that whatever change was done allow these decimals too round to two decimals.
Example of new extracted tsv:
"autoresolver_battle_max_melee_skirmish_time_proportion	0.8999999
autoresolver_battle_result_accuracy_high_prediction_variation	0.020000001
autoresolver_battle_result_accuracy_low_prediction_variation	0.20000002
autoresolver_battle_tower_base_kps	0.39000002
autoresolver_building_damage_num_units_percentage	0.010000002
autoresolver_casualty_unary_received_by_excess_melee_units_from_target	0.050000004
autoresolver_chase_down_damage_multiplier	1.0
autoresolver_max_hp_for_enemy_hp_dps_modifier	2000.0
autoresolver_min_battle_time_before_retreat	45.0
autoresolver_min_hp_for_enemy_hp_dps_modifier	600.0
autoresolver_num_excess_melee_units_receiving_casualties_from_target	4.0
autoresolver_num_units_multiplier_vs_enemy_to_allow_retreat	0.75
autoresolver_unit_base_retreat_threshold	0.2
autoresolver_unit_wipe_out_threshold	0.1
autoresolver_wall_damage_num_artillery_units_percentage	0.010000002"

**Comment by Frodo45127** [comment]
Fixed for the next update.
