### ISSUE TITLE
Notes Causes Consistent crash across games

### ISSUE THREAD

**Issue by gdwitt** [Frodo45127/rpfm#209]
When I right click on a directory and open-notes, it opens. When I type something or paste something it crashes the rpfm. Always.
Seen in Attila, Rome 2, Troy.
Using latest version.
I really liked this feature of RPFM. Big step up over PFM manager when it used to work in 2021.

**Comment by Frodo45127** [comment]
Finally found what caused this crash. Should be fixed in 3.0.11, when it finish building. Thanks for the report.
