### ISSUE TITLE
RPFM crashes on installing mods

### ISSUE THREAD

**Issue by wolphyx** [Frodo45127/rpfm#21]
**Describe your problem**
Since the newest update, whenever I try to "Install" one of my mods using the install button in the MyMod menu, RPFM crashes completely. This kills the modding workflow significantly, as I have to move files manually to the /data folder to test and/or upload them. I'd appreciate if this could be looked into.
Apart from that - I love the dark theme!

**Extra info?**
Version 1.3.2
For me this is reproducible with all of my MyMods.

**Comment by Frodo45127** [comment]
It seems it was a problem with some locks. Just fixed it a couple of hours ago for the next bugfix release. Thanks for the report!
