### ISSUE TITLE
CTD in Empire TW caused by a mod created in RPFM

### ISSUE THREAD

**Issue by azat11** [Frodo45127/rpfm#211]
**Describe your problem**

A mod created in RPFM crashes the game on launch, while the same mod made in PFM works perfectly.

I don't know what causes the crash. The game is Empire TW. The tables edited are _gun_type_to_projectiles_ and _gun_type_to_projectiles_, but they don't seem to be the issue.

The issue seems to be in RPFM. The game is chosen correctly in RPFM.

**Extra info?**

RPFM 3.0.14

**Comment by Trolldemorted** [comment]
Could you upload both packages? Then one could have a look at the differences

**Comment by azat11** [comment]
> Could you upload both packages? Then one could have a look at the differences

Sure. I just don't know how to upload anything here. Some outside hosting?

**Comment by Frodo45127** [comment]
Assuming the _r file is from RPFM and the other one is from PFM, are you sure the PFM one is not just datacoring? Because apart of the obvious fact that RPFM has one extra file (for the internal settings), the only thing I can see that can cause issues is the filenames. I mean, either rename the _r one with the same file names as the other one, or viceversa and see if both work/don't work.

**Comment by azat11** [comment]
> Assuming the _r file is from RPFM and the other one is from PFM, are you sure the PFM one is not just datacoring? Because apart of the obvious fact that the _r one has one extra file (for the internal settings), the only thing I can see that can cause issues is the filenames. I mean, either rename the _r one with the same file names as the other one, or viceversa and see if both work/don't work.

I rechecked with renaming: RPFM mod file doesn't work both ways, PFM file works both ways.
Btw, I forgot to mention the PFM mod file gives an error in RPFM when trying to open a table, here's the screenshot: https://ibb.co/b5bgRkg

What extra file? A file inside the file?..

**Comment by Trolldemorted** [comment]
Do you know which string is supposed to be in row 2 cell 6? Is it extraordinary compared to other strings?

**Comment by Frodo45127** [comment]
Ok I have no idea how did you get PFM to create that table, as it's version 2 and empire's version of that table only goes up to version 1, but anyway, I added the schema so RPFM can read it.  Update the schema and RPFM should be able to edit it.

**Comment by azat11** [comment]
> Do you know which string is supposed to be in row 2 cell 6? Is it extraordinary compared to other strings?

I don't know. Afaik there's nothing special about it.

**Comment by azat11** [comment]
> Ok I have no idea how did you get PFM to create that table, as it's version 2 and empire's version of that table only goes up to version 1, but anyway, I added it to the schema so RPFM can read it. Update the schema and RPFM should be able to edit it.

Does this mean I now can create mod with RPFM and it's gonna work?
