### ISSUE TITLE
Table: technology_node_sets | missing column: game_expansion_key

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#212]
Table: technology_node_sets | missing column: game_expansion_key

RPFM
![image](https://user-images.githubusercontent.com/73296797/189332914-39ca2a4a-a2bf-4abc-b21c-93afc6bce285.png)

Assembly Kit
![image](https://user-images.githubusercontent.com/73296797/189333254-0874100a-7d55-453e-88ec-49125047a1b3.png)

**Comment by Frodo45127** [comment]
Not a bug. The assembly kit doesn't export those columns and rpfm cannot read them.
