### ISSUE TITLE
MyMod import not reading TSV files

### ISSUE THREAD

**Issue by DontCallMeDari** [Frodo45127/rpfm#214]
I'm trying to download the community bug fix and modify it as described in the readMe here:
https://github.com/chadvandy/cbfm_wh3

I followed their directions but when I get to the "MyMod -> Import" part, it looks like this.  The tables aren't loading and if I try to add a table, it adds a db section onto the end instead.  The .lua and .png files are being read correctly, as far as I can tell.

![image](https://user-images.githubusercontent.com/112979904/189746632-07d3b466-29b3-46cc-b900-c7bad2444422.png)

It's my first time using gitHub so I might have done something wrong there.
The path for the repository is "C:\Users\[I'm not posting my real name]\Documents\Mod Backups\MyMod\zzz_community_bugfix_mod" and if I look in the "cbfm_wh3" subfolder I do see the folders for the mod and the tsv files.

My MyMod folder path is "C:/Users/[I'm not posting my real name]/Documents/Mod Backups/MyMod" if that matters.

**Extra info?**
Warhammer 3 RPFM version 3.0.14

**Comment by Frodo45127** [comment]
You did it wrong. DB, .vscode, .git.... must be under the .pack file, not inside a folder. Meaning yoiu put the cbfm_wh3 inside the folder where those folders were supposed to be before importing.

**Comment by DontCallMeDari** [comment]
It worked, thanks!
