### ISSUE TITLE
table: building_effect_context_expressions missingColumn: display_text

### ISSUE THREAD

**Issue by BlackSoulCZ** [Frodo45127/rpfm#215]
**Describe your problem**

game:
TW Warhammer 3
table:
building_effect_context_expressions
doesnt show column display_text

**Extra info?**

used version
3.0.14

**Comment by Frodo45127** [comment]
Not a bug. Some tables in AK have columns that get removed when exporting due to that column being used in locs, or in starpos, or just not being exported. RPFM, for obvious reasons, cannot read columns that doesn't exists anymore.
