### ISSUE TITLE
The install function doesn't work on windows due to filepath issues

### ISSUE THREAD

**Issue by wolphyx** [Frodo45127/rpfm#22]
**Describe your problem**
I don't want to annoy you or anything but the install function is still buggy. :) I get the following error when trying to use it on windows:

_Error while trying to copy one or more files to the following folder:
"Z:/SteamGames/SteamApps/common/Total War Rome II\\data\\wolphyx_medals.pack"_

Looks like a filepath issue, as the slashes and backslashes are inconsistent. I tried changing them to backslashes in the settings.json, but that just caused RPFM to don't read any settings at all anymore.

**Extra info?**
Occurs on RPFM 1.3.3 when using the install function

**Comment by Frodo45127** [comment]
Since you just closed it... I guess it was an issue in your end.
