### ISSUE TITLE
Failed build on  linux invalid type

### ISSUE THREAD

**Issue by engineer1109** [Frodo45127/rpfm#220]
```
error: failed to load manifest for workspace member `/media/wjl/D2/github/rpfm/rpfm_lib`

Caused by:
  failed to parse manifest at `/media/wjl/D2/github/rpfm/rpfm_lib/Cargo.toml`

Caused by:
  invalid type: map, expected a string for key `package.rust-version`
```

cargo build error
cargo 1.61.0
develop 0e7a4839dce5903240f391045b06364f48d923bd
linux

**Comment by Frodo45127** [comment]
Not a bug. RPFM on either master or develop branches require Rust 1.64 (when that "package.rust-version" thing was added) or newer. If you can't get it on your system, the last tag on the repo that supported older rust versions is v3.0.16. Just updated the docs to reflect the change too.
