### ISSUE TITLE
libgit2 error prevents rpfm opening

### ISSUE THREAD

**Issue by bajabaum** [Frodo45127/rpfm#223]
Hi, I'm trying to use rpfm on arch linux, I can install the package from AUR just fine <https://aur.archlinux.org/packages/rpfm-bin> but when I try to start it from terminal I get:
"rpfm_ui: error while loading shared libraries: libgit2.so.1.1: cannot open shared object file: No such file or directory"
I downgraded to libgit2 1.1 and tried again but then I get
"rpfm_ui: error while loading shared libraries: libgit2.so.1.5: cannot open shared object file: No such file or directory"
Does rpfm require both or am I doing something very wrong?

Love the program, first time trying to use it on linux.

**Comment by Frodo45127** [comment]
mmmm it seems I forgot to add libgit2 to the pkgbuild. Just added it and pushed the updated pkgbuild to the aur. Apart of that, the -bin package uses  libgit2.so.1.5. Not sure why it's asking for libgit2.so.1.1 for you, as I don't have it in my system and it works without it.

**Comment by bajabaum** [comment]
I updated rpfm and also libgit2 (which itself updated less than half an hour ago), threw in a system update for good measure, and it seems like it's working now, not sure why, but I'll take it, thanks.
