### ISSUE TITLE
Cannot found exe file with the 4.0 update

### ISSUE THREAD

**Issue by memet13007** [Frodo45127/rpfm#229]
Hello guys, 
I cannot found the exe files when i extract rpfm today, yesterday was working fine, I only have rpfm_cli and rpfm_ui.
Tried uninstall and reinstall.
![Capture d’écran (12)](https://user-images.githubusercontent.com/127595209/224478278-b3f2da2d-642a-4323-8c40-07ac2455d830.png)

**Comment by Frodo45127** [comment]
rpfm.exe has been removed as it's no longer needed. Launch from rpfm_ui.exe from now on.
