### ISSUE TITLE
4.0.0 edits crashes, TWW2

### ISSUE THREAD

**Issue by Okminji** [Frodo45127/rpfm#230]
Any edits made to data.pack in 4.0.0 crashed TWW2.  
Also happens to mods sometime, but it is inconsistent.

**Comment by Frodo45127** [comment]
Update to 4.0.1 immediately. 4.0.0 has a bug that corrupts tables with combined colour columns when saved.

**Comment by Frodo45127** [comment]
And for the love of god, never edit data.pack

**Comment by Okminji** [comment]
It's just to test why my mods seemingly killed the game, so I edited a random stat in data to be sure it was the editor and not my stupid *ss messing mods up. Also confirmed fixed in 4.0.1, thanks for your fast work.
