### ISSUE TITLE
Cannot load all CA pack files from total war three kingdoms since 4.0

### ISSUE THREAD

**Issue by memet13007** [Frodo45127/rpfm#231]
hello everybody, 
I Cannot load all CA pack files from total war three kingdoms since 4.0.
The game selected is 3k (default game) and i had been able to make a dependencie cash.
Thanks for your help

![Capture d’écran (13)](https://user-images.githubusercontent.com/127595209/224482186-a4f9a183-8649-41d9-85fd-71bf8e25be3a.png)

**Comment by Frodo45127** [comment]
Not a bug. It's disabled on purpose if you have generated the dependencies cache, because the data it loads it's already loaded in the dependencies panel.
