### ISSUE TITLE
New update broke me old version. New download has no .exe to run the program... WHY?

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#232]
Normally I update schemas when I come down to start modding.
Today, came down to do work and the new schemas broke my years old setup. 
Can't even do what I set out to do.
Pissed but hopefully this will be fixed soon.
Looks like its just a game day.

**Comment by Frodo45127** [comment]
As specified in the 4.0 release notes, the new schemas do not work with older versions of the program. Either update both, schemas and the program, or none. And 4.0 no longer has rpfm.exe. use rpfm_ui.exe insted.
