### ISSUE TITLE
Mass import/export tsv removed

### ISSUE THREAD

**Issue by GanjaNoel** [Frodo45127/rpfm#235]
Unfortunately I noticed the mass import/export tsv files feature was removed in the changelogs. Maybe the feature was a bit niche, but I actually found it very handy when modifying a large amount of tables outside of rpfm. Perhaps you can consider reimplementing it?

**Comment by Frodo45127** [comment]
As it says in 4.0.0 changelog, add and extract now do the exact same thing mass-import/export did. So use those instead.
