### ISSUE TITLE
Add folder issue

### ISSUE THREAD

**Issue by gorokhan** [Frodo45127/rpfm#236]
"Add folder" doesn't work or at least doesn't work as it used to be. When adding "db" folder from assembly_kit/working_data it skips creating "db" path in the mod and simply adds edited tables. So instead of mod.pack/db/edited_table it's mod.pack/edited_table now

**Extra info?**
<!--- "What version of RPFM did you used?" the latest, 4.0.4

**Comment by Frodo45127** [comment]
Fixed in 4.0.5 with the "include base folder in add from folder" setting.
