### ISSUE TITLE
Uses all my RAM then dumps and repeats. Version  4.0.17 -- 2.0 2

### ISSUE THREAD

**Issue by Casualfield** [Frodo45127/rpfm#251]
rpfm just randomly uses all my RAM (or caches what it can )and then dumps it all and goes back to normal for about 4 minutes then repeats, indefinitely.  
Just afk with data.pack open not doing anything. It's not my pc with a memory leak. Paged pool and Non-paged pool are under 500MB, it's 100% just rpfm, can include video if needed.

Version 
4.0.17 -- 2.0 2: Electric Boogaloo Patch, Only For The Brave
Feature flags enabled: support_rigidmodel, support_modern_dds, enable_tools, only_for_the_brave
![memory disc usage](https://user-images.githubusercontent.com/75649150/234983052-15ff176c-93ca-44df-b220-e766c7875aa8.png)
![ram usage](https://user-images.githubusercontent.com/75649150/234983058-2fa46d63-9d51-4724-b01f-0b3adcc8b713.png)

**Comment by Frodo45127** [comment]
Do you have the game path set up correctly in the settings?

**Comment by Casualfield** [comment]
> Yes
![settings](https://user-images.githubusercontent.com/75649150/234990333-dd71bf2d-162c-4ffc-bb1e-8f3cea182a14.png)

**Comment by Frodo45127** [comment]
Fixed in 4.0.18. It was a bug that caused ca packs to not be properly identified and ignored on windows.
