### ISSUE TITLE
Failed to generate the dependencies cache (os error 2)

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [Frodo45127/rpfm#258]
Total War THREE KINGDOMS
![image](https://github.com/Frodo45127/rpfm/assets/30216016/509149cc-5dd3-42a7-9433-7b5de08017f0)
Error in path: E:\SteamLibrary\steamapps\common\Total War THREE KINGDOMS\data\audio.pack. 系统找不到指定的文件。 (os error 2)
![image](https://github.com/Frodo45127/rpfm/assets/30216016/7f9be1aa-878f-4b00-b55f-a82b3a6ea7e0)
and failed to open database from dependencies
![image](https://github.com/Frodo45127/rpfm/assets/30216016/91f8e2ed-5d73-42b0-8fce-b2e0c22e3074)
I tried to roll back the rpfm version ([Release v4.0.19](https://github.com/Frodo45127/rpfm/releases/tag/v4.0.19)), these problems were solved
![image](https://github.com/Frodo45127/rpfm/assets/30216016/1707c608-2452-4e9e-95e3-69faea34d64d)

**Comment by jasonPeng8314** [comment]
same situaction.

**Comment by Qwerty12008** [comment]
same here

**Comment by Frodo45127** [comment]
Fixed in 4.0.22
