### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by Sandvich682** [Frodo45127/rpfm#259]
I just downloaded RPFM's most recent version (4.0.22) and for some reason it is refusing to download any schemas for WH3.  Ive tried everything and every time I hit the "Update Schemas" I get this message:

reference 'refs/head/master' not found; class=Reference (4);
code=UnbornBranch (-9)

As a side note im not sure if rpfm_cli is supposed to do anything but any help would be appreciated

**Comment by Frodo45127** [comment]
Go to PackFile/Settings and hit "Clear Schema Folder" and try again. If it's a broken local schema repo, that should fix it.

**Comment by Sandvich682** [comment]
> Go to PackFile/Settings and hit "Clear Schema Folder" and try again. If it's a broken local schema repo, that should fix it.

Worked beautifully, much appreciated
