### ISSUE TITLE
Generate Ids integer limit

### ISSUE THREAD

**Issue by erikkgagewhitt** [Frodo45127/rpfm#262]
**Describe your problem**
When generating ids, for some reason there is an integer limit despite those integers working in-game. For example: generating ids from the integer `2213160316` is not possible and will instead start from 0. Additionally `2213160316` cannot be entered when generating ids without a starting value already entered.

**Extra info?**

v. 4.0.22

**Comment by Frodo45127** [comment]
If I remember correctly this was due a limitation displaying numbers bigger than that in the spinboxes, should be possible to make it work with bigger numbers for the next release.

**Comment by erikkgagewhitt** [comment]
Sweet! Thank ya much!

**Comment by Frodo45127** [comment]
Done for 4.1.0
