### ISSUE TITLE
Where .exe file?

### ISSUE THREAD

**Issue by whereistheexe** [Frodo45127/rpfm#263]
Downloads here: https://github.com/Frodo45127/rpfm/releases

FAQ
Why there is no .exe in the download?: because you downloaded the source code, not the program. Check at the begining of this description, where is says Downloads here.

Downloads here: https://github.com/Frodo45127/rpfm/releases

Where???? which release? is it included in every release?? i downloaded the non source ones and no exe.

**Comment by Trolldemorted** [comment]
![image](https://github.com/Frodo45127/rpfm/assets/10261186/999d662d-21a2-4dd1-aee6-ce75aa880570)

Every release has a zip with windows binaries and a tar with linux binaries

**Comment by Kronav** [comment]
Think I'm having the same issue, the exe file is not in the zip for me as well.

![ne1](https://github.com/Frodo45127/rpfm/assets/140850271/fd8055bb-c608-43b6-a3b3-aaf1943e685b)

**Comment by Frodo45127** [comment]
The exe is called rpfm_ui.exe, and it's in all windows releases.
