### ISSUE TITLE
Wrong file path for WH3

### ISSUE THREAD

**Issue by JoenvandeVorle** [Frodo45127/rpfm#269]
For some reason, RPFM while looking for the data folder for WH3 tries to look in TotalWarWARHAMMERIII\share/data/data instead of TotalWarWARHAMMERIII/data. I am using the epic games version of the game so that may be related. the share/data/data folder doesn't exist, and for some reason it also uses a mix of forward and backslashes.

![image](https://github.com/Frodo45127/rpfm/assets/90771356/083a3b9a-dc3f-452f-8852-16a9e4057799)

**Comment by Frodo45127** [comment]
I don't have wh3 on epic to test it, so for wh3 if it's not a windows - steam install, rpfm considers it a linux-steam install, which has that path. You can create a "steam_api.dll" on the exe folder to trick RPFM into thinking it's a steam install of the game, but not sure if it'll explode somewhere else.

**Comment by JoenvandeVorle** [comment]
This seems to work so far, thanks!
