### ISSUE TITLE
Can not set pack file type to movie using rpfm_cli

### ISSUE THREAD

**Issue by ilia-sharafutdinov** [Frodo45127/rpfm#270]
Hi Frodo!

I'm trying to convert a simple Empire Total War pack with only DB entries inside from mod to movie using CLI. However, the command fails with some Rust-specific error and conversion does not happen.

**OS:** Ubuntu 22.04.3 LTS

**The command:**
`rpfm_cli --game empire pack set-file-type --pack-path Empire\ Total\ War/data/tgg_core.pack --file-type movie`

**The output:**
```
10:47:55 [INFO] Logger initialized.
10:47:55 [INFO] Sentry Logging support enabled. Starting...
10:47:55 [WARN] Panic detected. Generating backtraces and crash logs...
thread 'main' panicked at 'Mismatch between definition and access of `file_type`. Could not downcast to TypeId { t: 5125290391915687110 }, need to downcast to TypeId { t: 7975126953263805836 }
', /home/ilia/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.21/src/parser/error.rs:32:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Frodo45127** [comment]
Fixed for the next beta, or 4.2, whatever comes first.
