### ISSUE TITLE
WH3:  "Character Skill Node Sets" column missing from "character_skill_nodes_tables"

### ISSUE THREAD

**Issue by iDave1066** [Frodo45127/rpfm#273]
Rusted PFM v4.1.3, with most current schema as of 01 OCT 23.

Problem:  In Warhammer 3, "db/character_skill_nodes_tables/data__" is missing the column/link to "db/character_skill_node_sets_tables/data__"

Description:  In the Warhammer 3 DB table "character_skill_nodes_tables", "Character Skill Node Sets" should be the column immediately after "Character Skill Key", and instead it is simply missing.

**Comment by Frodo45127** [comment]
Not a bug. From the update info for 4.0 in the modding den discord:

> character skill nodes: IMPORTANT, junction with node sets now happens in a separate junction, character_skill_node_set_items_tables, which comes with a disable boolean for mods or it'd be datacore galore. Presumably saves data for shared skills like Mentor or red lines. Copy your node and node set stuff here BEFORE you update the schema for skill nodes.

So you need to use that new table instead.
