### ISSUE TITLE
Fails to compile rpfm_ui on Linux

### ISSUE THREAD

**Issue by Liemaeu** [Frodo45127/rpfm#278]
**Describe your problem**

When I try to compile rpfm on openSUSE Tumbleweed I get the error:

`error: linking with gcc-13 failed: exit status: 1`

gcc is installed (version 13-1.6).

**Extra info?**

Full output: https://gist.github.com/Liemaeu/69e45fc9cea110952678ffa54c073963

**Comment by Frodo45127** [comment]
in the output, it complains at the end that a few of kde libs were not found (no such file or directory). Install them, then try again.

**Comment by Liemaeu** [comment]
They should be installed. E.g. libKF5Completion5, libKF5IconThemes5, libKF5XmlGui5 and libKF5WidgetsAddons5 are all installed on my system.

**Comment by Liemaeu** [comment]
Finally found the missing packages! It wasn't the libKF5... packages as the error message mentions, they are named k...-devel on openSUSE. Now it compiles. Thank you!
