### ISSUE TITLE
"About" -> "Check Updates" button stopped working on Ubuntu 22.04.3 LTS since around 4.2

### ISSUE THREAD

**Issue by ilia-sharafutdinov** [Frodo45127/rpfm#279]
After pressing "About" -> "Check Updates" button, an error message appears, reading:

`No such file or directory (os error 2)`

![Screenshot from 2023-11-26 20-47-02](https://github.com/Frodo45127/rpfm/assets/60923483/cada8d26-e325-462e-b15a-224e07ad32e5)

**Comment by Frodo45127** [comment]
No idea about this one. It's not reproducible in arch, and I neither use nor provide an ubuntu package. My guess it's is missing the new ui template file for the updater, which is the only file I remember that's loaded when opening the update manager, but that's on the linux release package and on the arch pkgbuilds, so don't know.
