### ISSUE TITLE
Faction Painter, Unit Editor and Translator tools are not not enabled at compile time on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by ilia-sharafutdinov** [Frodo45127/rpfm#280]
I'm using the [4.2.3 source code upload](https://github.com/Frodo45127/rpfm/releases/download/v4.2.3/rpfm-v4.2.3-x86_64-unknown-linux-gnu.tar.zst) and trying to compile it with `cargo build --release`.

**Comment by Frodo45127** [comment]
Tools require the "enable_tools" feature to be enabled when compiling with cargo to work. If you want to manually compile rpfm and use them, enable that feature.

**Comment by ilia-sharafutdinov** [comment]
How do I enable the tools?

**Comment by Frodo45127** [comment]
Done.
