### ISSUE TITLE
Question: Reading Pack Files

### ISSUE THREAD

**Issue by ev3nst** [Frodo45127/rpfm#285]
I want to be able to see contents of the pack file using node.js so i can compare multiple pack files if they have conflict. I have made some extensive search on google but just cant find enough information for pack files. I thought maybe people here would like to help me understand how can i implement this.

**Comment by Frodo45127** [comment]
All the code for reading packs is here: https://github.com/Frodo45127/rpfm/tree/master/rpfm_lib/src/files/pack It should contain what you're asking for.

**Comment by ev3nst** [comment]
Unfortunetly i do not know rust and on top of that what is achieved here is a bit complex. Ill try my best but i'd be really thankful if there was some more guidelines i can follow, understand what is being done instead of trying to translate line by line to javascript.  otherwise there is i think 3000 lines of code that needs translating
