### ISSUE TITLE
Editor works great now. Needs access to a DB file in Attila DB.

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#286]
Please add missile_weapons_models(_tables) to your Attila list.

**Comment by Frodo45127** [comment]
That table is empty in the game (cannot be decoded) and doesn't even exists in the Assembly Kit (meaning is unused by the game and cannot be created even with the official tools).

**Comment by magus721** [comment]
Got ya. If it was possible, you likely would have done it already. Thanks for the response and the update.
