### ISSUE TITLE
Empty Key Fields/Unit Editor

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#287]
Platform: Attila

"db/mount_variants_tables/mount_variants" is has empty or missing key fields.

Unit Editor doesn't seem to want to work.

**Comment by Frodo45127** [comment]
The unit editor tool is only supported on Warhammer 2. Not sure how did you trigger it for Attila, as RPFM should grey out its button if you select an incompatible game, but it's not supported for it.

**Comment by magus721** [comment]
Ok thanks
