### ISSUE TITLE
new version error

### ISSUE THREAD

**Issue by Leonardusius** [Frodo45127/rpfm#294]
the application v4.3.2 was unable ..........0xc0000005 on windows 7 64 bit. Never had any issues with RPFM till now. Also i don"t see rpfm.exe file no more. Is this intended ? No more support for win7 ?

**Comment by Frodo45127** [comment]
No idea (I don't test on win7), but nothing has change between 4.3.1 and 4.3.2 that may cause an incompatibility. Searching online for that specific error tells me that may be a ram problem on your side. I suggest you do a pass with memtest86, just in case.

**Comment by Leonardusius** [comment]
No. Memory OK. Same with the newer version, I think it don't work with win7 anymore. Apart, there are only 2 .exe now: rpfm_ui and rpfm_clim when in the older versions were more.

**Comment by Leonardusius** [comment]
After banging my head a lot here it is: ''This isn't a request for support, I've been struggling with this for a couple of days and finally found the culprit. I'm thus writing this merely to share my findings with others. Rust has in https://github.com/rust-lang/compiler-team/issues/651 (and with good help from Microsoft I'm sure) decided to stop supporting all Windows versions before Windows 10 (for a programming language that is quite serious, and this is a good reason to stay way clear of Rust) after version 1.75.

The result when trying to run an executable compiled with a more recent version of rust is the following error:

The procedure entry point ProcessPrng could not be located in the dynamic link library bcryptprimitives.dll.''

Please compile with Rust 1.75 to give us win7 compatibility.
Thank you.

**Comment by Leonardusius** [comment]
> No idea (I don't test on win7), but nothing has change between 4.3.1 and 4.3.2 that may cause an incompatibility. Searching online for that specific error tells me that may be a ram problem on your side. I suggest you do a pass with memtest86, just in case.

After banging my head a lot here it is: ''This isn't a request for support, I've been struggling with this for a couple of days and finally found the culprit. I'm thus writing this merely to share my findings with others. Rust has in https://github.com/rust-lang/compiler-team/issues/651 (and with good help from Microsoft I'm sure) decided to stop supporting all Windows versions before Windows 10 (for a programming language that is quite serious, and this is a good reason to stay way clear of Rust) after version 1.75.

The result when trying to run an executable compiled with a more recent version of rust is the following error:

The procedure entry point ProcessPrng could not be located in the dynamic link library bcryptprimitives.dll.''

Please compile with Rust 1.75 to give us win7 compatibility.
Thank you.

**Comment by Frodo45127** [comment]
Try 4.3.8. I downgraded the compiler to 1.75, but no guarantee it'll work in windows 7.

**Comment by Leonardusius** [comment]
> Try 4.3.8. I downgraded the compiler to 1.75, but no guarantee it'll work in windows 7.

It works very well. Just as I predicted. Thank you very much.
