### ISSUE TITLE
Last version with rpfm.exe

### ISSUE THREAD

**Issue by Leonardusius** [Frodo45127/rpfm#297]
What is the last version with the rpfm.exe file, please ? Because it is the last one to be used with Windows 7. Thank you

**Comment by Frodo45127** [comment]
Newer releases should work (at least for now) with windows 7, so no old release is needed.

**Comment by Leonardusius** [comment]
Thank you very much. Just compiling with what i pointed and all will work with Win7. And is always compatible upwards. 
Cheers.
