### ISSUE TITLE
Error when opening any pack file

### ISSUE THREAD

**Issue by Solmyr77a** [Frodo45127/rpfm#298]
Getting "Error: The file with the path --booted_from_launcher hasn't been found on this Pack" popup whenever I open a pack file. Doesn't seem to cause anything bad, but how do I get rid of it?

**Comment by Frodo45127** [comment]
Delete rpfm.exe and use rpfm_ui.exe instead. rpfm.exe is an old exe that's no longer distributed and it's what's causing the error message.
