### ISSUE TITLE
Is it possible to update "trait_attribute_effects_tables" in the Total War: Attila DB?

### ISSUE THREAD

**Issue by magus721** [Frodo45127/rpfm#299]
I would like to have access to this table to mod ineffectual traits and improve upon them. 

Thank you in advance.

**Comment by Frodo45127** [comment]
Not sure what you mean with "update". You mean add columns?

**Comment by magus721** [comment]
Yes, please add it to your next schema update for Total War Attila.
This database file governs trait effects parameters and there are a number of traits that need a rework.
Also, some traits added by the Medieval Kingdoms 1212AD team will not work properly without modification to this file.

**Comment by Frodo45127** [comment]
Mmmm for what I can see, this table doesn't even exist in attila's Assembly Kit. Meaning it cannot be exported nor decoded.

**Comment by magus721** [comment]
oof...setback
