### ISSUE TITLE
Thrones of Brittania failure to generate startpos

### ISSUE THREAD

**Issue by Napolitain** [Frodo45127/rpfm#302]
**Describe your problem**

**For Attila**

Can't generate startpos for Attila Total War main campaign

**Extra info?**
- Latest release, schemas
- Successfully created Last Roman campaign in Attila
- For some reason, normal campaign doesn't create

![image](https://github.com/user-attachments/assets/c24bd68a-45f0-48a8-86ac-70388dcb7622)

For **ToB**

- similar process for creating
- game stuck at launch time (no crash nothing)

**Comment by Napolitain** [comment]
update: attila worked, I didn't put 0 to every place where it had to be  done (btw, there is a table, think start_pos_regions, where owning factions set to 0 doesnt trigger an error, when it should. I think it should be fixed.
ToB still doesnt work

**Comment by Frodo45127** [comment]
This should be fixed in 4.3.10. Remember to re-import the AK tables in 4.3.10 (in case it's a rogue 0 somewhere) before trying again.
