### ISSUE TITLE
Packfile invalid name : is it really invalid ?

### ISSUE THREAD

**Issue by Napolitain** [Frodo45127/rpfm#303]
I made some mistakes i guess renaming my file and then uploading to Workshop.
![image](https://github.com/user-attachments/assets/d6c2a617-aefe-42dd-abaa-59866fe37350)

that file isn't recognized by RPFM as valid name. I think it is a overly strict check by RPFM but I could be wrong, as technically it is really just a normal name and I think it works just fine in the workshop.

I suggest either affirming it is an important check, or removing it.

**Comment by Frodo45127** [comment]
The pack name contains spaces, which depending on the game/system may crash the game on launch. So the diagnostic is correct, though it may be game-dependant.
