### ISSUE TITLE
Game Paths used internally only work on Windows.

### ISSUE THREAD

**Issue by Frodo45127** [Frodo45127/rpfm#37]
Linux paths are... diferrent. Feral ports have their data in multiple separate subfolders instead in a common "data/" folder. So we need to expand the path system to admit multiple ones, and use X or Y paths depending on what's in their base folder. So far we got:
- ***Windows***: all games use the path `game_folder/data`. 
- ***Linux***: depends on the game:
    - ***Warhammer 2***: Feral Port. It uses `game_folder/share/data/data` for the base game's data.
    - ***Warhammer***: No idea.
    - ***Thrones of Britannia***: No idea.
    - ***Attila***: In-House Port. No idea.
    - ***Rome 2***: No idea.
    - ***Shogun 2***: Feral Port. It uses `game_folder/share/data/data` for the base game, and `game_folder/share/data/fots` for FOTS-Specific PackFiles.
    - ***Napoleon***: No idea.
    - ***Empire***: No idea.
- ***MacOS***: I don't have a Mac to test, so no idea, but in theory if this gets fixed there are not many problems to build RPFM for MacOS and release a Mac version.

**Comment by Dirk-c-Walter** [comment]
Checking on warhammer 2 it looks like it uses;
Total War WARHAMMER II/share/data/data/

Anything in specific I shoudl check for?

**Comment by Frodo45127** [comment]
Just the OS. That path is on mac or linux?

**Comment by Dirk-c-Walter** [comment]
That is on Linux.

**Comment by Frodo45127** [comment]
Thanks. I just added it to the list. I'll see if I can get the path thing fixed for the next update, so RPFM can try to gess the paths instead using a fixed one....

**Comment by Frodo45127** [comment]
Finally got around and fixed this.
