### ISSUE TITLE
Support for older titles?

### ISSUE THREAD

**Issue by Maetharin** [Frodo45127/rpfm#4]
Sorry if I have in any way overlooked things, but will this support older titles like Rome 2 or Atilla? 
I mostly work on these.

Splendid work btw!

**Comment by Frodo45127** [comment]
Thanks! Already answered on reddit, but for the records, yes, they'll be supported, but supporting a game means it needs to work with all the stuff already implemented, so not only I need time to implement encoding/decoding support for them, but also I need to do an schema for them, and make sure that works with every feature in RPFM. And that takes time. So I'll like to go one game at a time. I'll try to get Warhammer 1 support for the next update, then Attila's, them Rome II. Support for older games than that.... It's not planned. At least not until after 1.0 is released.
