### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by Maetharin** [Frodo45127/rpfm#6]
Really sorry if this seems noobish or anything, but how do I install this tool?

I´m a small time modder and I´d love to try out the new Attila compability, 
but I haven´t been able to run this at all. Can´t seem to find any executable.

**Comment by Frodo45127** [comment]
Just download the rar file of the last release, uncompress it somewhere in your PC, and run ```rpfm-code.exe```. It should be in the folder you uncompressed. And, after that, go to ```PackFile/Preferences```, configure everything you needed there (specially the Path for Attila). The open an Attila PackFile, got to ```Special Stuff/Attila/Generate Dependency Pack``` and wait until the program responds again.

That's more or less a "How to install & first start" guide for Atilla.

**Comment by Frodo45127** [comment]
I'll close this, as it seem there are no more questions.
